repos:
  - repo: local
    hooks:
      - id: lint-all-notebooks-with-black
        name: lint-all-notebooks-with-black
        files: \.ipynb
        stages: [pre-push, manual]
        language: system
        entry: poetry run nbqa black . && git add * && git commit -m "Apply black to all files"
