"""
Consolidated beam-splitter unitary implementations.

Provides three core beam-splitter unitary constructors, each operating in a
different Hilbert space:

- ``bs_fock``: two-mode Fock space (uses a†a₂ + a₂†a₁ generator).
- ``bs_qubit``: single-qubit space (uses σ_x/2 generator).
- ``bs_dicke``: single-subsystem Dicke basis (uses collective J_x generator).

Tensor-product wrappers (e.g., ``kron(bs_qubit(T), bs_qubit(T))``) are left to
the calling code or kept as convenience functions in the original modules.

Convention reference:
    =============== =================== =============
    Function        50/50 value         Generator
    =============== =================== =============
    ``bs_fock``     θ = π/4            a†a₂ + h.c.
    ``bs_qubit``    T = π/2            σ_x / 2
    ``bs_dicke``    T = π/2            collective J_x
    =============== =================== =============

The factor-of-2 difference between θ and T arises because
J_x = (a†a₂ + a₂†a¹)/2, so exp(-i·θ·H_bs) = exp(-i·(2θ)·J_x).
Thus θ_bs = T_bs / 2.

A special case exists in ``src/physics/hybrid_mzi.py:mzi_beam_splitter``,
which uses the different generator ``G = i(a₁†a₂ - a₁a₂†)`` in an embedded
two-mode + spin space and is kept in that module.

Post-BS Variance Reference:
    For a 50/50 beam splitter (θ = π/4, φ_bs = 0) using the generator
    H_BS = a_0^† a_1 + a_1^† a_0 and J_z = (n_0 - n_1)/2, the variance
    of J_z after the first beam splitter (BS1) for common input states is:

    ================== ========================= =========================
    Input State        Var(J_z) after BS1        Notes
    ================== ========================= =========================
    NOON |N,0⟩+|0,N⟩    N/4                      BS1 does NOT preserve
                                                 NOON for N>1; to obtain
                                                 Heisenberg-limited QFI
                                                 (F_Q = H_t^2 N^2), skip
                                                 BS1 and use the input
                                                 state directly.
    Twin-Fock           N(N+2)/8                  Near-Heisenberg
    |N/2,N/2⟩                                    variance from the
                                                 binomial expansion.
    Coherent |α,α⟩      |α|²/2                   SQL-classical scaling
                                                 (Var proportional to
                                                 mean photon number).
    ================== ========================= =========================

    For states already constructed in the post-BS1 form (e.g. as probe
    states after an effective BS1), the variance is simply the variance
    of the input state itself.  See reports/20260601/ for CFI-based
    verification and the effect of skipping BS1 for NOON states.
"""

from __future__ import annotations

from functools import cache

import numpy as np
import scipy.linalg
import scipy.sparse

from src.physics.dicke_basis import jx_operator
from src.utils.constants import I_2, SIGMA_X
from src.utils.enums import OperatorBasis


@cache
def bs_fock(
    theta: float,
    phi_bs: float,
    max_photons: int,
    auto_sparse_threshold: int = 50,
) -> np.ndarray | scipy.sparse.spmatrix:
    r"""Two-mode Fock space beam-splitter unitary.

    Mode transformation:
        a → cos(θ)·a + i·e^{iφ}·sin(θ)·b
        b → cos(θ)·b - i·e^{-iφ}·sin(θ)·a

    Generated by H = e^{iφ} a₁†a₂ + e^{-iφ} a₂†a₁, U = exp(-iθ H).

    For a symmetric 50/50 beam splitter, use θ = π/4.
    The phase φ controls the reflection amplitude phase.

    Uses a block-diagonal decomposition over total photon number N = n₁ + n₂,
    which avoids a full (M+1)²× (M+1)² matrix exponential by computing
    expm on each (N+1)×(N+1) subspace independently.

    For ``max_photons > auto_sparse_threshold`` (default 50), the unitary is
    stored as a ``scipy.sparse.csr_matrix`` to avoid allocating O(dim²) memory.
    The sparse format is fully compatible with ``@`` (matvec and matmul),
    ``.shape``, ``.conj().T``, and ``np.kron``.

    Args:
        theta: Beam-splitter transmittance angle. θ = 0 gives identity,
            θ = π/4 gives 50/50.
        phi_bs: Phase shift applied to reflected photons.
        max_photons: Maximum photon number per mode for truncation.
        auto_sparse_threshold: ``max_photons`` above this value uses sparse CSR.

    Returns:
        Unitary (dense ndarray or sparse CSR matrix) of dimension
        (max_photons + 1)² × (max_photons + 1)².

    """
    dim = (max_photons + 1) ** 2
    use_sparse = max_photons > auto_sparse_threshold
    U = _allocate_bs_matrix(dim, use_sparse)

    for n_total in range(2 * max_photons + 1):
        k_min = max(0, n_total - max_photons)
        k_max = min(max_photons, n_total)
        n_sub = k_max - k_min + 1
        if n_sub <= 0:
            continue
        U_sub = _build_bs_subspace_block(n_total, k_min, k_max, phi_bs, theta)
        _place_subspace_block(U, U_sub, n_total, k_min, k_max, max_photons)

    if use_sparse:
        U_lil: scipy.sparse.lil_matrix = U  # type: ignore[assignment]
        U_csr = U_lil.tocsr()
        _verify_sparse_bs_unitarity(U_csr, max_photons)
        return U_csr

    U_dense: np.ndarray = U  # type: ignore[assignment]
    _verify_dense_bs_unitarity(U_dense, max_photons)
    return U_dense


def _allocate_bs_matrix(
    dim: int,
    use_sparse: bool,
) -> scipy.sparse.lil_matrix | np.ndarray:
    """Allocate a dim×dim matrix for the beam-splitter unitary."""
    if use_sparse:
        return scipy.sparse.lil_matrix((dim, dim), dtype=complex)
    return np.zeros((dim, dim), dtype=complex)


def _build_bs_subspace_block(
    n_total: int,
    k_min: int,
    k_max: int,
    phi_bs: float,
    theta: float,
) -> np.ndarray:
    """Build H_sub and return expm(-i·θ·H_sub) for the subspace.

    In the |k, n-k⟩ basis, H_sub has matrix elements:
        ⟨k+1, n-k-1|H|k, n-k⟩ = e^{iφ}·√((k+1)(n-k))
    """
    n_sub = k_max - k_min + 1
    H_sub = np.zeros((n_sub, n_sub), dtype=complex)
    for idx, k in enumerate(range(k_min, k_max)):
        val = np.sqrt((k + 1) * (n_total - k))
        H_sub[idx, idx + 1] = val * np.exp(1j * phi_bs)
        H_sub[idx + 1, idx] = val * np.exp(-1j * phi_bs)
    return scipy.linalg.expm(-1.0j * theta * H_sub)


def _place_subspace_block(
    U: np.ndarray | scipy.sparse.lil_matrix,
    U_sub: np.ndarray,
    n_total: int,
    k_min: int,
    k_max: int,
    max_photons: int,
) -> None:
    """Place a subspace block U_sub into the full beam-splitter matrix U."""
    for idx_k, k in enumerate(range(k_min, k_max + 1)):
        i_out = k * (max_photons + 1) + (n_total - k)
        for idx_l, lp in enumerate(range(k_min, k_max + 1)):
            j_out = lp * (max_photons + 1) + (n_total - lp)
            U[i_out, j_out] = U_sub[idx_k, idx_l]


def _verify_dense_bs_unitarity(
    U_dense: np.ndarray,
    max_photons: int,
) -> None:
    """Verify unitarity of a dense BS matrix via full check or column-norm sampling."""
    dim_check = U_dense.shape[0]
    if dim_check <= 400:
        _eye = np.eye(dim_check, dtype=complex)
        assert np.allclose(U_dense @ U_dense.conj().T, _eye, atol=1e-10), (
            f"Beam splitter not unitary for max_photons={max_photons}"
        )
    else:
        norms = np.sum(np.abs(U_dense[:, :10]) ** 2, axis=0)
        assert np.allclose(norms, 1.0, atol=1e-10), (
            f"Beam splitter column norms deviate from 1: "
            f"max_dev={np.max(np.abs(norms - 1.0))}"
        )


def _verify_sparse_bs_unitarity(
    U: scipy.sparse.csr_matrix,
    max_photons: int,
) -> None:
    """Verify unitarity of a sparse BS matrix via column-norm sampling."""
    n_cols = min(10, U.shape[1])
    # Extract columns as dense submatrix (small: n_cols <= 10)
    cols_dense = U[:, :n_cols].toarray()
    norms = np.sum(np.abs(cols_dense) ** 2, axis=0)
    assert np.allclose(norms, 1.0, atol=1e-10), (
        f"Sparse beam splitter column norms deviate from 1: "
        f"max_dev={np.max(np.abs(norms - 1.0))} "
        f"for max_photons={max_photons}"
    )


@cache
def bs_qubit(T_BS: float) -> np.ndarray:
    """Single-qubit beam-splitter unitary generated by J_x.

    U_BS(T_BS) = exp(-i T_BS J_x) = cos(T_BS/2) I - i sin(T_BS/2) σ_x

    A 50/50 beam splitter corresponds to T_BS = π/2.

    Args:
        T_BS: Beam-splitter duration.

    Returns:
        2×2 unitary matrix.

    """
    U = np.cos(T_BS / 2.0) * I_2 - 1j * np.sin(T_BS / 2.0) * SIGMA_X
    assert np.allclose(U @ U.conj().T, I_2, atol=1e-12), (
        f"BS unitary not unitary for T_BS={T_BS}"
    )
    return U


@cache
def bs_dicke(N: int, T_BS: float = np.pi / 2.0) -> np.ndarray:
    """Single-subsystem Dicke-basis beam-splitter unitary (cached by N and T_BS).

    U_BS = exp(-i T_BS J_x)

    Results are cached by (N, T_BS) to avoid repeated matrix exponentiation.

    Args:
        N: Particle number (dim = N + 1).
        T_BS: Beam-splitter angle (default π/2 for 50/50).

    Returns:
        (N + 1) × (N + 1) unitary matrix.

    """
    Jx = jx_operator(N, basis=OperatorBasis.DICKE)
    U = scipy.linalg.expm(-1j * T_BS * Jx)
    assert np.allclose(U @ U.conj().T, np.eye(N + 1), atol=1e-12)
    return U
