"""
Ancilla-Assisted Metrology Optimisation via Nelder–Mead — Core Physics.

Implements the core operators, state preparation, circuit evolution, and
sensitivity computation for a two-qubit (system + ancilla) Mach–Zehnder
interferometer estimating an unknown phase rate ω.

Physical Model:
- Two qubits: system (S) and ancilla (A), each isomorphic to a spin-½.
- Basis: {|1,0⟩, |0,1⟩} for each qubit (single-particle subspace).
- Beam splitters: generated by J_x with optimisable duration T.
- Holding Hamiltonian:
    H_hold = ω J_z^S + H_int(α)
    H_int = α_xx J_x^S⊗J_x^A + α_xz J_x^S⊗J_z^A + α_zx J_z^S⊗J_x^A + α_zz J_z^S⊗J_z^A
- Measurement: J_z^S on the system qubit.
- Sensitivity: Δω via error propagation (central finite differences).

Units:
- Dimensionless throughout. ω is the unknown phase rate (radians per unit time).
- t_hold: holding-time strength (dimensionless).
- α coefficients: real coupling strengths.

References:
- Giovannetti, Lloyd, Maccone, Nat. Photonics 5, 222 (2011)
- Davis et al., PRA 94, 063814 (2016)
- Kitagawa & Ueda, PRA 47, 5138 (1993)
- Hentschel & Sanders, PRA 88, 062329 (2013)

"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache

import numpy as np

from src.physics.beam_splitter import bs_qubit
from src.utils.constants import I_2, I_4, J_X, J_Y, J_Z, SIGMA_X, SIGMA_Z


@dataclass
class _DebugConfig:
    """Gated-debug configuration for operator assertions.

    Set ``verify_operators=True`` in unit tests to verify operator
    properties on every call.  When ``False`` (optimisation hot path),
    expensive assertions are skipped.
    """

    verify_operators: bool = False


# Module-level singleton.  Unit tests can set ``_debug.verify_operators = True``
# to enable cold-path assertion checks without changing call signatures.
_debug = _DebugConfig()


def _expm_hermitian(H: np.ndarray, t: float) -> np.ndarray:
    """Exponentiate a Hermitian matrix ``exp(-i t H)`` via ``eigh``.

    For a small (4×4) Hermitian matrix this is 2–3× faster than
    ``scipy.linalg.expm`` because it exploits Hermiticity.
    """
    eigvals, eigvecs = np.linalg.eigh(H)
    return eigvecs @ np.diag(np.exp(-1j * t * eigvals)) @ eigvecs.conj().T


# ============================================================================
# Operator Construction
# ============================================================================


def build_two_qubit_operators() -> dict[str, np.ndarray]:
    """Build the 4×4 operators for the two-qubit system.

    Basis ordering (computational basis):
        |0⟩_S|0⟩_A, |0⟩_S|1⟩_A, |1⟩_S|0⟩_A, |1⟩_S|1⟩_A
    where |0⟩ = |1,0⟩ (particle in mode 0), |1⟩ = |0,1⟩ (particle in mode 1).

    Returns:
        Dict with keys 'Jz_S', 'Jz_A', 'Jx_S', 'Jx_A', 'Jy_S', 'Jy_A',
        each a 4×4 complex Hermitian matrix.

    """
    return {
        "Jz_S": np.kron(J_Z, I_2),
        "Jz_A": np.kron(I_2, J_Z),
        "Jx_S": np.kron(J_X, I_2),
        "Jx_A": np.kron(I_2, J_X),
        "Jy_S": np.kron(J_Y, I_2),
        "Jy_A": np.kron(I_2, J_Y),
    }


def build_interaction_hamiltonian(
    alpha: tuple[float, float, float, float],
) -> np.ndarray:
    """Build the system–ancilla interaction Hamiltonian.

    H_int = α_xx · J_x^S ⊗ J_x^A + α_xz · J_x^S ⊗ J_z^A
          + α_zx · J_z^S ⊗ J_x^A + α_zz · J_z^S ⊗ J_z^A

    Args:
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.

    Returns:
        4×4 Hermitian interaction matrix.

    """
    a_xx, a_xz, a_zx, a_zz = alpha

    # Tensor-product operators: J_i^S ⊗ J_j^A  =  (σ_i/2) ⊗ (σ_j/2) = σ_i ⊗ σ_j / 4
    # Pre-compute the four tensor products
    xx = np.kron(SIGMA_X / 2, SIGMA_X / 2)  # J_x^S ⊗ J_x^A
    xz = np.kron(SIGMA_X / 2, SIGMA_Z / 2)  # J_x^S ⊗ J_z^A
    zx = np.kron(SIGMA_Z / 2, SIGMA_X / 2)  # J_z^S ⊗ J_x^A
    zz = np.kron(SIGMA_Z / 2, SIGMA_Z / 2)  # J_z^S ⊗ J_z^A

    H = np.zeros((4, 4), dtype=complex)
    if a_xx != 0.0:
        H += a_xx * xx
    if a_xz != 0.0:
        H += a_xz * xz
    if a_zx != 0.0:
        H += a_zx * zx
    if a_zz != 0.0:
        H += a_zz * zz
    return H


# ============================================================================
# State Preparation
# ============================================================================


def single_qubit_state(theta: float, phi_Bloch: float) -> np.ndarray:
    """Create a single-qubit pure state on the Bloch sphere.

    |ψ⟩ = cos(θ/2) |0⟩ + e^{iφ} sin(θ/2) |1⟩

    where |0⟩ = |1,0⟩ (particle in mode 0), |1⟩ = |0,1⟩ (particle in mode 1).

    Args:
        theta: Polar angle ∈ [0, π].
        phi_Bloch: Azimuthal angle ∈ [0, 2π).

    Returns:
        Normalised complex 2-vector.

    """
    return np.array(
        [np.cos(theta / 2.0), np.exp(1j * phi_Bloch) * np.sin(theta / 2.0)],
        dtype=complex,
    )


def two_qubit_state(
    theta_S: float,
    phi_S: float,
    theta_A: float,
    phi_A: float,
) -> np.ndarray:
    """Create a product state |ψ_S⟩ ⊗ |ψ_A⟩.

    Args:
        theta_S: Polar angle for system qubit.
        phi_S: Azimuthal angle for system qubit.
        theta_A: Polar angle for ancilla qubit.
        phi_A: Azimuthal angle for ancilla qubit.

    Returns:
        Normalised complex 4-vector (product state).

    """
    psi_S = single_qubit_state(theta_S, phi_S)
    psi_A = single_qubit_state(theta_A, phi_A)
    return np.kron(psi_S, psi_A)


def free_ancilla_initial_state(theta_A: float, phi_A: float) -> np.ndarray:
    r"""Construct the system--ancilla product initial state.

    :math:`|\Psi_0\rangle = |1,0\rangle_S \otimes |\psi_A(\theta_A, \phi_A)\rangle`

    where :math:`|\psi_A\rangle = \cos(\theta_A/2)\,|1,0\rangle_A
    + e^{i\phi_A}\sin(\theta_A/2)\,|0,1\rangle_A`.

    Args:
        theta_A: Ancilla polar angle :math:`\in [0, \pi]`.
        phi_A: Ancilla azimuthal angle :math:`\in [0, 2\pi)`.

    Returns:
        Normalised 4-vector in the :math:`\{|00\rangle, |01\rangle, |10\rangle,
        |11\rangle\}` basis.
    """
    psi_S = np.array([1.0, 0.0], dtype=complex)  # |1,0⟩_S
    psi_A = single_qubit_state(theta_A, phi_A)
    state = np.kron(psi_S, psi_A)
    if _debug.verify_operators:
        assert np.isclose(np.linalg.norm(state), 1.0), (
            "Free-ancilla initial state must be normalised"
        )
    return state


# ============================================================================
# Beam-Splitter Unitaries
# ============================================================================


@lru_cache(maxsize=8)
def bs_unitary(T_BS: float) -> np.ndarray:
    """Single-qubit beam-splitter unitary generated by J_x.

    U_BS(T_BS) = exp(-i T_BS J_x) = cos(T_BS/2) I - i sin(T_BS/2) σ_x

    A 50/50 beam splitter corresponds to T_BS = π/2.

    Args:
        T_BS: Beam-splitter duration (optimisable parameter).

    Returns:
        2×2 unitary matrix.

    """
    return bs_qubit(T_BS)


@lru_cache(maxsize=8)
def two_qubit_bs_unitary(T_BS: float) -> np.ndarray:
    """Two-qubit beam-splitter unitary: U_BS(T_BS) ⊗ U_BS(T_BS).

    Args:
        T_BS: Beam-splitter duration.

    Returns:
        4×4 unitary matrix (tensor product).

    """
    return np.kron(bs_unitary(T_BS), bs_unitary(T_BS))


# ============================================================================
# Holding Hamiltonian & Unitary
# ============================================================================


def build_hold_hamiltonian(
    omega: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
) -> np.ndarray:
    """Build the full holding Hamiltonian.

    H_hold = ω J_z^S + H_int(α)

    Args:
        omega: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators from build_two_qubit_operators().

    Returns:
        4×4 Hermitian Hamiltonian matrix.

    """
    H_int = build_interaction_hamiltonian(alpha)
    H = omega * ops["Jz_S"] + H_int
    # Ensure Hermiticity
    return 0.5 * (H + H.conj().T)


def hold_unitary_two_qubit(
    t_hold: float,
    omega: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
) -> np.ndarray:
    """Holding-time unitary for the 2-qubit ancilla system.

    U_hold(t_hold) = exp(-i t_hold H_hold)

    Args:
        t_hold: Holding-time strength.
        omega: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators from build_two_qubit_operators().

    Returns:
        4×4 unitary matrix.

    """
    H = build_hold_hamiltonian(omega, alpha, ops)
    U = _expm_hermitian(H, t_hold)
    if _debug.verify_operators:
        assert np.allclose(U @ U.conj().T, I_4, atol=1e-12), (
            f"Hold unitary not unitary for t_hold={t_hold}, ω={omega}, α={alpha}"
        )
    return U


# ============================================================================
# Full Circuit Evolution
# ============================================================================


def evolve_full(
    psi0: np.ndarray,
    T_BS1: float,
    T_BS2: float,
    t_hold: float,
    omega: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
) -> np.ndarray:
    """Run the full MZI circuit.

    |ψ_final⟩ = U_BS(T_BS2) · U_hold(t_hold, ω, α) · U_BS(T_BS1) · |ψ₀⟩

    Args:
        psi0: Initial 4-vector (product state).
        T_BS1: First beam-splitter duration.
        T_BS2: Second beam-splitter duration.
        t_hold: Holding-time strength.
        omega: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators.

    Returns:
        Final 4-vector state.

    Raises:
        AssertionError: If input state is not normalised.

    Constraints:
        psi0 must be normalized 4-vector.
        T_BS1, T_BS2, t_hold > 0.
        omega real (phase rate parameter).
        alpha tuple must be length 4: (α_xx, α_xz, α_zx, α_zz).
        ops must contain keys for all required two-qubit operators.

    """
    if _debug.verify_operators:
        assert np.isclose(np.linalg.norm(psi0), 1.0), "Initial state must be normalised"

    psi = two_qubit_bs_unitary(T_BS1) @ psi0
    psi = hold_unitary_two_qubit(t_hold, omega, alpha, ops) @ psi
    psi = two_qubit_bs_unitary(T_BS2) @ psi

    if _debug.verify_operators:
        assert np.isclose(np.linalg.norm(psi), 1.0), "Final state must be normalised"
    return psi


# ============================================================================
# Sensitivity Computation (Error Propagation)
# ============================================================================


def build_joint_operator(ops: dict[str, np.ndarray]) -> np.ndarray:
    """Build the joint measurement operator M = J_z^S + J_z^A.

    Args:
        ops: Two-qubit operators from build_two_qubit_operators().

    Returns:
        4×4 Hermitian matrix representing the joint measurement.

    """
    return ops["Jz_S"] + ops["Jz_A"]


def compute_covariance(
    psi: np.ndarray,
    ops: dict[str, np.ndarray],
) -> float:
    """Compute Cov(J_z^S, J_z^A) = ⟨J_z^S J_z^A⟩ - ⟨J_z^S⟩⟨J_z^A⟩.

    Args:
        psi: Normalised state vector (4-component).
        ops: Two-qubit operators (must contain 'Jz_S', 'Jz_A').

    Returns:
        Covariance between J_z^S and J_z^A measurements.

    """
    Jz_S = ops["Jz_S"]
    Jz_A = ops["Jz_A"]

    exp_S = np.real(psi.conj() @ Jz_S @ psi)
    exp_A = np.real(psi.conj() @ Jz_A @ psi)
    exp_SA = np.real(psi.conj() @ (Jz_S @ Jz_A) @ psi)

    cov = exp_SA - exp_S * exp_A
    # Covariance can be legitimately negative (anti-correlation).
    # Only check for NaN/Inf and that it lies in the mathematically
    # allowed range: |Cov(X,Y)| ≤ sqrt(Var(X) * Var(Y)).
    assert np.isfinite(cov), f"Covariance is not finite: Cov = {cov}"
    return float(cov)


def compute_expectation_and_variance(
    psi: np.ndarray,
    operator: np.ndarray,
) -> tuple[float, float]:
    """Compute ⟨ψ|O|ψ⟩ and Var(O) = ⟨O²⟩ - ⟨O⟩² for a pure state.

    Args:
        psi: Normalised state vector.
        operator: Hermitian operator matrix.

    Returns:
        Tuple (expectation, variance).

    """
    exp_val = np.real(psi.conj() @ operator @ psi)
    op_sq = operator @ operator
    exp_sq = np.real(psi.conj() @ op_sq @ psi)
    raw_var = exp_sq - exp_val**2
    # Numerical rounding can produce tiny negative variances (~1e-16).
    # Assert that variance is not significantly negative (physics error).
    if _debug.verify_operators:
        assert raw_var >= -1e-12, (
            f"Unphysical negative variance: Var = {raw_var:.2e} (expectation = {exp_val:.6f})"
        )
    # Clamp residual round-off noise (typically O(1e-16)) to zero.
    var_val = max(0.0, raw_var)
    return float(exp_val), float(var_val)


def compute_reduced_purity(psi: np.ndarray) -> float:
    """Purity of the reduced density matrix of the system qubit.

    For a two-qubit pure state |ψ⟩ ∈ ℂ⁴ in the basis
    {|00⟩, |01⟩, |10⟩, |11⟩}, the reduced density matrix of the
    system qubit is ρ_S = Tr_A(|ψ⟩⟨ψ|).  Purity = Tr(ρ_S²).

    For a product state, purity = 1.  For a maximally entangled
    Bell state, purity = 0.5.

    Args:
        psi: Normalised 4-vector two-qubit state.

    Returns:
        Purity Tr(ρ_S²) ∈ [0.5, 1.0].

    """
    # psi components: [⟨00|ψ⟩, ⟨01|ψ⟩, ⟨10|ψ⟩, ⟨11|ψ⟩]
    # Reduced density matrix ρ_S = Tr_A(|ψ⟩⟨ψ|):
    #   ρ_S[0,0] = |⟨00|ψ⟩|² + |⟨01|ψ⟩|²   (prob. system in |0⟩)
    #   ρ_S[1,1] = |⟨10|ψ⟩|² + |⟨11|ψ⟩|²   (prob. system in |1⟩)
    #   ρ_S[0,1] = ⟨00|ψ⟩⟨ψ|10⟩ + ⟨01|ψ⟩⟨ψ|11⟩  (coherence)
    rho_00 = abs(psi[0]) ** 2 + abs(psi[1]) ** 2
    rho_11 = abs(psi[2]) ** 2 + abs(psi[3]) ** 2
    rho_01 = psi[0] * np.conj(psi[2]) + psi[1] * np.conj(psi[3])
    purity = rho_00**2 + rho_11**2 + 2.0 * abs(rho_01) ** 2
    # Assert the mathematically expected range [0.5, 1.0].
    # Outside this range indicates a computation error, not numerical noise.
    assert 0.5 - 1e-12 <= purity <= 1.0 + 1e-12, (
        f"Purity {purity:.15f} outside expected range [0.5, 1.0]"
    )
    return float(purity)


def compute_sensitivity(
    psi0: np.ndarray,
    T_BS1: float,
    T_BS2: float,
    t_hold: float,
    omega_true: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
    fd_step: float = 1e-6,
    meas_op: np.ndarray | None = None,
) -> float:
    """Compute the error-propagation sensitivity Δω.

    Δω = sqrt(Var(O)) / |∂⟨O⟩/∂ω|

    where O is the measurement operator (default: J_z^S).

    The derivative is computed via central finite differences.

    Args:
        psi0: Initial 4-vector (product state).
        T_BS1: First beam-splitter duration.
        T_BS2: Second beam-splitter duration.
        t_hold: Holding-time strength.
        omega_true: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators (must contain 'Jz_S').
        fd_step: Finite-difference step size (default 1e-6).
        meas_op: Measurement operator. Defaults to ops['Jz_S'] (S-only).

    Returns:
        Sensitivity Δω (positive float).

    Raises:
        RuntimeError: If derivative is zero (operating at fringe extremum).

    """
    if meas_op is None:
        meas_op = ops["Jz_S"]

    # Evaluate at omega_true
    psi = evolve_full(psi0, T_BS1, T_BS2, t_hold, omega_true, alpha, ops)
    _, var = compute_expectation_and_variance(psi, meas_op)

    # Central finite difference for ∂⟨O⟩/∂θ
    psi_plus = evolve_full(psi0, T_BS1, T_BS2, t_hold, omega_true + fd_step, alpha, ops)
    psi_minus = evolve_full(
        psi0,
        T_BS1,
        T_BS2,
        t_hold,
        omega_true - fd_step,
        alpha,
        ops,
    )
    exp_plus = np.real(psi_plus.conj() @ meas_op @ psi_plus)
    exp_minus = np.real(psi_minus.conj() @ meas_op @ psi_minus)
    d_exp = (exp_plus - exp_minus) / (2.0 * fd_step)

    if abs(d_exp) < 1e-12:
        # Derivative is effectively zero → fringe extremum
        return float("inf")

    return float(np.sqrt(var) / abs(d_exp))


# ============================================================================
# Objective Function for Optimisation
# ============================================================================


def _params_to_components(
    params: np.ndarray,
) -> tuple[
    float,
    float,
    float,
    float,
    float,
    float,
    float,
    tuple[float, float, float, float],
]:
    """Unpack the 11-element parameter vector into named components.

    Parameter order:
        [θ_S, φ_S, θ_A, φ_A, T_BS1, T_BS2, t_hold, α_xx, α_xz, α_zx, α_zz]
        Note: θ_S, θ_A are Bloch sphere polar angles, NOT the phase rate ω.

    Args:
        params: 11-element array of optimisation parameters.

    Returns:
        Tuple (theta_S, phi_S, theta_A, phi_A, T_BS1, T_BS2, t_hold, alpha).

    """
    theta_S = float(params[0])
    phi_S = float(params[1])
    theta_A = float(params[2])
    phi_A = float(params[3])
    T_BS1 = float(params[4])
    T_BS2 = float(params[5])
    t_hold = float(params[6])
    alpha: tuple[float, float, float, float] = (
        float(params[7]),
        float(params[8]),
        float(params[9]),
        float(params[10]),
    )
    return theta_S, phi_S, theta_A, phi_A, T_BS1, T_BS2, t_hold, alpha


def _enforce_bounds(
    theta_S: float,
    theta_A: float,
    phi_S: float,
    phi_A: float,
    T_BS1: float,
    T_BS2: float,
    t_hold: float,
    alpha: tuple[float, float, float, float],
    bounds: dict[str, tuple[float, float]],
    penalty_scale: float = 1e6,
    fixed_alpha: tuple[float, float, float, float] | None = None,
) -> float:
    """Enforce parameter bounds via quadratic penalty.

    Args:
        theta_S: System polar angle.
        theta_A: Ancilla polar angle.
        phi_S: System azimuthal angle.
        phi_A: Ancilla azimuthal angle.
        T_BS1: First beam-splitter duration.
        T_BS2: Second beam-splitter duration.
        t_hold: Holding-time strength.
        alpha: 4-element interaction coefficient tuple.
        bounds: Dict of parameter bounds.
        penalty_scale: Scale for bound-violation penalty.
        fixed_alpha: If set, alpha bound checks are skipped.

    Returns:
        Total penalty (0.0 if no violation).

    """
    penalty = 0.0
    for val, key in [
        (theta_S, "bloch_theta"),
        (theta_A, "bloch_theta"),
        (phi_S, "phi"),
        (phi_A, "phi"),
        (T_BS1, "T_BS"),
        (T_BS2, "T_BS"),
        (t_hold, "t_hold"),
    ]:
        lo, hi = bounds[key]
        if val < lo:
            penalty += penalty_scale * (lo - val) ** 2
        if val > hi:
            penalty += penalty_scale * (val - hi) ** 2
    if fixed_alpha is None:
        for i in range(4):
            lo, hi = bounds["alpha"]
            if alpha[i] < lo:
                penalty += penalty_scale * (lo - alpha[i]) ** 2
            if alpha[i] > hi:
                penalty += penalty_scale * (alpha[i] - hi) ** 2
    return penalty


def sensitivity_objective(
    params: np.ndarray,
    omega_true: float,
    ops: dict[str, np.ndarray],
    fd_step: float = 1e-6,
    bounds: dict[str, tuple[float, float]] | None = None,
    penalty_scale: float = 1e6,
    meas_op: np.ndarray | None = None,
    fixed_alpha: tuple[float, float, float, float] | None = None,
) -> float:
    """Objective function for minimising Δω.

    Args:
        params: 11-element optimisation parameter vector, or 7-element
            state-only vector when fixed_alpha is set.
        omega_true: True phase rate parameter.
        ops: Two-qubit operators.
        fd_step: Finite-difference step size.
        bounds: Dict of parameter bounds (defaults to report values).
        penalty_scale: Scale for bound-violation penalty.
        meas_op: Measurement operator. Defaults to ops['Jz_S'].
        fixed_alpha: If set, params is a 7-element state vector;
            fixed_alpha is prepended to form the full 11-element vector.
            Alpha bound checks are skipped in this mode.

    Returns:
        Δω value (plus infinite penalty if bounds violated).

    """
    # Default bounds from the report
    if bounds is None:
        bounds = get_default_bounds()

    # If fixed_alpha is set, params is 7-element (state only);
    # prepend fixed_alpha to make 11 elements.
    if fixed_alpha is not None:
        params = np.concatenate([params, np.asarray(fixed_alpha, dtype=float)])

    theta_S, phi_S, theta_A, phi_A, T_BS1, T_BS2, t_hold, alpha = _params_to_components(
        params,
    )

    # Bound enforcement (penalty method)
    penalty = _enforce_bounds(
        theta_S,
        theta_A,
        phi_S,
        phi_A,
        T_BS1,
        T_BS2,
        t_hold,
        alpha,
        bounds,
        penalty_scale,
        fixed_alpha,
    )
    if penalty > 0.0:
        return float(1e10 + penalty)

    # Build initial state
    psi0 = two_qubit_state(theta_S, phi_S, theta_A, phi_A)

    # Compute sensitivity
    return compute_sensitivity(
        psi0,
        T_BS1,
        T_BS2,
        t_hold,
        omega_true,
        alpha,
        ops,
        fd_step,
        meas_op=meas_op,
    )


# ============================================================================
# Parameter Utilities
# ============================================================================


def get_default_bounds() -> dict[str, tuple[float, float]]:
    """Get the default parameter bounds.

    Returns:
        Dict with keys 'theta', 'phi', 'T_BS', 't_hold', 'alpha' mapping to
        (min, max) tuples.

    """
    return {
        "bloch_theta": (0.0, np.pi),
        "phi": (0.0, 2.0 * np.pi),
        "T_BS": (0.0, np.pi),
        "t_hold": (0.0, 5.0),
        "alpha": (-2.0, 2.0),
    }


def random_initial_params(
    rng: np.random.Generator,
    bounds: dict[str, tuple[float, float]] | None = None,
) -> np.ndarray:
    """Generate random initial parameters within the search bounds.

    All 11 parameters are drawn independently from their respective bounds.

    Args:
        rng: Random number generator.
        bounds: Optional custom bounds (uses defaults if None).

    Returns:
        11-element array of initial parameters.

    """
    if bounds is None:
        bounds = get_default_bounds()

    theta_lo, theta_hi = bounds["bloch_theta"]
    phi_lo, phi_hi = bounds["phi"]
    tbs_lo, tbs_hi = bounds["T_BS"]
    th_lo, th_hi = bounds["t_hold"]
    alpha_lo, alpha_hi = bounds["alpha"]

    theta_S, theta_A = rng.uniform(theta_lo, theta_hi, size=2)
    phi_S, phi_A = rng.uniform(phi_lo, phi_hi, size=2)
    T_BS1, T_BS2 = rng.uniform(tbs_lo, tbs_hi, size=2)
    t_hold = rng.uniform(th_lo, th_hi)
    alpha = rng.uniform(alpha_lo, alpha_hi, size=4)
    return np.array(
        [theta_S, phi_S, theta_A, phi_A, T_BS1, T_BS2, t_hold, *alpha],
        dtype=float,
    )


# ============================================================================
# Diagnostics
# ============================================================================


def diagnostics_from_params(
    params: np.ndarray,
    omega_true: float,
    ops: dict[str, np.ndarray],
) -> tuple[float, float, float, float, float, float]:
    """Compute diagnostics (expectations, variances, covariance, purity) at a given parameter vector.

    Args:
        params: 11-element parameter vector (θ_S, φ_S, θ_A, φ_A, T_BS1, T_BS2, t_hold, α_xx, α_xz, α_zx, α_zz).
        omega_true: True phase rate parameter.
        ops: Two-qubit operators from build_two_qubit_operators().

    Returns:
        Tuple (exp_Jz, var_Jz, exp_M, var_M, cov_SA, purity).

    """
    (
        opt_theta_S,
        opt_phi_S,
        opt_theta_A,
        opt_phi_A,
        opt_T_BS1,
        opt_T_BS2,
        opt_t_hold,
        opt_alpha,
    ) = _params_to_components(params)
    opt_psi0 = two_qubit_state(opt_theta_S, opt_phi_S, opt_theta_A, opt_phi_A)
    opt_psi = evolve_full(
        opt_psi0,
        opt_T_BS1,
        opt_T_BS2,
        opt_t_hold,
        omega_true,
        opt_alpha,
        ops,
    )

    # Always compute both S-only and joint measurement diagnostics
    exp_val_s, var_val_s = compute_expectation_and_variance(opt_psi, ops["Jz_S"])
    M_op = build_joint_operator(ops)
    exp_val_m, var_val_m = compute_expectation_and_variance(opt_psi, M_op)
    cov_sa = compute_covariance(opt_psi, ops)
    purity = compute_reduced_purity(opt_psi)

    return exp_val_s, var_val_s, exp_val_m, var_val_m, cov_sa, purity
