"""
Ancilla-Assisted Metrology Optimization via Nelder–Mead.

Implements the full-parameter optimisation of a two-qubit (system + ancilla)
Mach–Zehnder interferometer for estimating an unknown phase rate θ.

Physical Model:
- Two qubits: system (S) and ancilla (A), each isomorphic to a spin-½.
- Basis: {|1,0⟩, |0,1⟩} for each qubit (single-particle subspace).
- Beam splitters: generated by J_x with optimisable duration T.
- Holding Hamiltonian:
    H_hold = θ J_z^S + H_int(α)
    H_int = α_xx J_x^S⊗J_x^A + α_xz J_x^S⊗J_z^A + α_zx J_z^S⊗J_x^A + α_zz J_z^S⊗J_z^A
- Measurement: J_z^S on the system qubit.
- Sensitivity: Δθ via error propagation (central finite differences).

Units:
- Dimensionless throughout. θ is the unknown phase rate (radians per unit time).
- T_H: holding-time strength (dimensionless).
- α coefficients: real coupling strengths.

References:
- Giovannetti, Lloyd, Maccone, Nat. Photonics 5, 222 (2011)
- Davis et al., PRA 94, 063814 (2016)
- Kitagawa & Ueda, PRA 47, 5138 (1993)
- Hentschel & Sanders, PRA 88, 062329 (2013)
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
from scipy.linalg import expm
from scipy.optimize import minimize


# ============================================================================
# Physical Constants & Pauli Matrices
# ============================================================================

# Pauli matrices (dimensionless)
SIGMA_X: np.ndarray = np.array([[0, 1], [1, 0]], dtype=complex)
SIGMA_Y: np.ndarray = np.array([[0, -1j], [1j, 0]], dtype=complex)
SIGMA_Z: np.ndarray = np.array([[1, 0], [0, -1]], dtype=complex)
I_2: np.ndarray = np.eye(2, dtype=complex)

# Angular-momentum operators for a single qubit (J = σ/2)
J_X: np.ndarray = SIGMA_X / 2.0
J_Y: np.ndarray = SIGMA_Y / 2.0
J_Z: np.ndarray = SIGMA_Z / 2.0


# ============================================================================
# Operator Construction
# ============================================================================


def build_two_qubit_operators() -> dict[str, np.ndarray]:
    """Build the 4×4 operators for the two-qubit system.

    Basis ordering (computational basis):
        |0⟩_S|0⟩_A, |0⟩_S|1⟩_A, |1⟩_S|0⟩_A, |1⟩_S|1⟩_A
    where |0⟩ = |1,0⟩ (particle in mode 0), |1⟩ = |0,1⟩ (particle in mode 1).

    Returns:
        Dict with keys 'Jz_S', 'Jz_A', 'Jx_S', 'Jx_A', 'Jy_S', 'Jy_A',
        each a 4×4 complex Hermitian matrix.
    """
    return {
        "Jz_S": np.kron(J_Z, I_2),
        "Jz_A": np.kron(I_2, J_Z),
        "Jx_S": np.kron(J_X, I_2),
        "Jx_A": np.kron(I_2, J_X),
        "Jy_S": np.kron(J_Y, I_2),
        "Jy_A": np.kron(I_2, J_Y),
    }


def build_interaction_hamiltonian(
    alpha: tuple[float, float, float, float],
) -> np.ndarray:
    """Build the system–ancilla interaction Hamiltonian.

    H_int = α_xx · J_x^S ⊗ J_x^A + α_xz · J_x^S ⊗ J_z^A
          + α_zx · J_z^S ⊗ J_x^A + α_zz · J_z^S ⊗ J_z^A

    Args:
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.

    Returns:
        4×4 Hermitian interaction matrix.
    """
    a_xx, a_xz, a_zx, a_zz = alpha

    # Tensor-product operators: J_i^S ⊗ J_j^A  =  (σ_i/2) ⊗ (σ_j/2) = σ_i ⊗ σ_j / 4
    # Pre-compute the four tensor products
    xx = np.kron(SIGMA_X / 2, SIGMA_X / 2)  # J_x^S ⊗ J_x^A
    xz = np.kron(SIGMA_X / 2, SIGMA_Z / 2)  # J_x^S ⊗ J_z^A
    zx = np.kron(SIGMA_Z / 2, SIGMA_X / 2)  # J_z^S ⊗ J_x^A
    zz = np.kron(SIGMA_Z / 2, SIGMA_Z / 2)  # J_z^S ⊗ J_z^A

    H = np.zeros((4, 4), dtype=complex)
    if a_xx != 0.0:
        H += a_xx * xx
    if a_xz != 0.0:
        H += a_xz * xz
    if a_zx != 0.0:
        H += a_zx * zx
    if a_zz != 0.0:
        H += a_zz * zz
    return H


# ============================================================================
# State Preparation
# ============================================================================


def single_qubit_state(theta: float, phi: float) -> np.ndarray:
    """Create a single-qubit pure state on the Bloch sphere.

    |ψ⟩ = cos(θ/2) |0⟩ + e^{iφ} sin(θ/2) |1⟩

    where |0⟩ = |1,0⟩ (particle in mode 0), |1⟩ = |0,1⟩ (particle in mode 1).

    Args:
        theta: Polar angle ∈ [0, π].
        phi: Azimuthal angle ∈ [0, 2π).

    Returns:
        Normalised complex 2-vector.
    """
    return np.array(
        [np.cos(theta / 2.0), np.exp(1j * phi) * np.sin(theta / 2.0)], dtype=complex
    )


def two_qubit_state(
    theta_S: float, phi_S: float, theta_A: float, phi_A: float
) -> np.ndarray:
    """Create a product state |ψ_S⟩ ⊗ |ψ_A⟩.

    Args:
        theta_S: Polar angle for system qubit.
        phi_S: Azimuthal angle for system qubit.
        theta_A: Polar angle for ancilla qubit.
        phi_A: Azimuthal angle for ancilla qubit.

    Returns:
        Normalised complex 4-vector (product state).
    """
    psi_S = single_qubit_state(theta_S, phi_S)
    psi_A = single_qubit_state(theta_A, phi_A)
    return np.kron(psi_S, psi_A)


# ============================================================================
# Beam-Splitter Unitaries
# ============================================================================


def bs_unitary(T: float) -> np.ndarray:
    """Single-qubit beam-splitter unitary generated by J_x.

    U_BS(T) = exp(-i T J_x) = cos(T/2) I - i sin(T/2) σ_x

    A 50/50 beam splitter corresponds to T = π/2.

    Args:
        T: Beam-splitter duration (optimisable parameter).

    Returns:
        2×2 unitary matrix.
    """
    U = np.cos(T / 2.0) * I_2 - 1j * np.sin(T / 2.0) * SIGMA_X
    assert np.allclose(U @ U.conj().T, I_2, atol=1e-12), (
        f"BS unitary not unitary for T={T}"
    )
    return U


def two_qubit_bs_unitary(T: float) -> np.ndarray:
    """Two-qubit beam-splitter unitary: U_BS(T) ⊗ U_BS(T).

    Args:
        T: Beam-splitter duration.

    Returns:
        4×4 unitary matrix (tensor product).
    """
    U = bs_unitary(T)
    return np.kron(U, U)


# ============================================================================
# Holding Hamiltonian & Unitary
# ============================================================================


def build_hold_hamiltonian(
    theta: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
) -> np.ndarray:
    """Build the full holding Hamiltonian.

    H_hold = θ J_z^S + H_int(α)

    Args:
        theta: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators from build_two_qubit_operators().

    Returns:
        4×4 Hermitian Hamiltonian matrix.
    """
    H_int = build_interaction_hamiltonian(alpha)
    H = theta * ops["Jz_S"] + H_int
    # Ensure Hermiticity
    H = 0.5 * (H + H.conj().T)
    return H


def hold_unitary(
    T_H: float,
    theta: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
) -> np.ndarray:
    """Holding-time unitary.

    U_hold(T_H) = exp(-i T_H H_hold)

    Args:
        T_H: Holding-time strength.
        theta: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators from build_two_qubit_operators().

    Returns:
        4×4 unitary matrix.
    """
    H = build_hold_hamiltonian(theta, alpha, ops)
    U = expm(-1j * T_H * H)
    I_4 = np.eye(4, dtype=complex)
    assert np.allclose(U @ U.conj().T, I_4, atol=1e-12), (
        f"Hold unitary not unitary for T_H={T_H}, θ={theta}, α={alpha}"
    )
    return U


# ============================================================================
# Full Circuit Evolution
# ============================================================================


def evolve_full(
    psi0: np.ndarray,
    T_BS1: float,
    T_BS2: float,
    T_H: float,
    theta: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
) -> np.ndarray:
    """Run the full MZI circuit.

    |ψ_final⟩ = U_BS(T_BS2) · U_hold(T_H, θ, α) · U_BS(T_BS1) · |ψ₀⟩

    Args:
        psi0: Initial 4-vector (product state).
        T_BS1: First beam-splitter duration.
        T_BS2: Second beam-splitter duration.
        T_H: Holding-time strength.
        theta: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators.

    Returns:
        Final 4-vector state.

    Raises:
        AssertionError: If input state is not normalised.
    """
    assert np.isclose(np.linalg.norm(psi0), 1.0), "Initial state must be normalised"

    psi = two_qubit_bs_unitary(T_BS1) @ psi0
    psi = hold_unitary(T_H, theta, alpha, ops) @ psi
    psi = two_qubit_bs_unitary(T_BS2) @ psi

    assert np.isclose(np.linalg.norm(psi), 1.0), "Final state must be normalised"
    return psi


# ============================================================================
# Sensitivity Computation (Error Propagation)
# ============================================================================


def compute_expectation_and_variance(
    psi: np.ndarray, operator: np.ndarray
) -> tuple[float, float]:
    """Compute ⟨ψ|O|ψ⟩ and Var(O) = ⟨O²⟩ - ⟨O⟩² for a pure state.

    Args:
        psi: Normalised state vector.
        operator: Hermitian operator matrix.

    Returns:
        Tuple (expectation, variance).
    """
    exp_val = np.real(psi.conj() @ operator @ psi)
    op_sq = operator @ operator
    exp_sq = np.real(psi.conj() @ op_sq @ psi)
    raw_var = exp_sq - exp_val**2
    # Numerical rounding can produce tiny negative variances (~1e-16).
    # Assert that variance is not significantly negative (physics error).
    assert raw_var >= -1e-12, (
        f"Unphysical negative variance: Var = {raw_var:.2e} (expectation = {exp_val:.6f})"
    )
    # Clamp residual round-off noise (typically O(1e-16)) to zero.
    var_val = max(0.0, raw_var)
    return float(exp_val), float(var_val)


def compute_reduced_purity(psi: np.ndarray) -> float:
    """Purity of the reduced density matrix of the system qubit.

    For a two-qubit pure state |ψ⟩ ∈ ℂ⁴ in the basis
    {|00⟩, |01⟩, |10⟩, |11⟩}, the reduced density matrix of the
    system qubit is ρ_S = Tr_A(|ψ⟩⟨ψ|).  Purity = Tr(ρ_S²).

    For a product state, purity = 1.  For a maximally entangled
    Bell state, purity = 0.5.

    Args:
        psi: Normalised 4-vector two-qubit state.

    Returns:
        Purity Tr(ρ_S²) ∈ [0.5, 1.0].
    """
    # psi components: [⟨00|ψ⟩, ⟨01|ψ⟩, ⟨10|ψ⟩, ⟨11|ψ⟩]
    # Reduced density matrix ρ_S = Tr_A(|ψ⟩⟨ψ|):
    #   ρ_S[0,0] = |⟨00|ψ⟩|² + |⟨01|ψ⟩|²   (prob. system in |0⟩)
    #   ρ_S[1,1] = |⟨10|ψ⟩|² + |⟨11|ψ⟩|²   (prob. system in |1⟩)
    #   ρ_S[0,1] = ⟨00|ψ⟩⟨ψ|10⟩ + ⟨01|ψ⟩⟨ψ|11⟩  (coherence)
    rho_00 = abs(psi[0]) ** 2 + abs(psi[1]) ** 2
    rho_11 = abs(psi[2]) ** 2 + abs(psi[3]) ** 2
    rho_01 = psi[0] * np.conj(psi[2]) + psi[1] * np.conj(psi[3])
    purity = rho_00**2 + rho_11**2 + 2.0 * abs(rho_01) ** 2
    # Assert the mathematically expected range [0.5, 1.0].
    # Outside this range indicates a computation error, not numerical noise.
    assert 0.5 - 1e-12 <= purity <= 1.0 + 1e-12, (
        f"Purity {purity:.15f} outside expected range [0.5, 1.0]"
    )
    return float(purity)


def compute_sensitivity(
    psi0: np.ndarray,
    T_BS1: float,
    T_BS2: float,
    T_H: float,
    theta_true: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
    fd_step: float = 1e-6,
) -> float:
    """Compute the error-propagation sensitivity Δθ.

    Δθ = sqrt(Var(J_z^S)) / |∂⟨J_z^S⟩/∂θ|

    The derivative is computed via central finite differences.

    Args:
        psi0: Initial 4-vector (product state).
        T_BS1: First beam-splitter duration.
        T_BS2: Second beam-splitter duration.
        T_H: Holding-time strength.
        theta_true: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators (must contain 'Jz_S').
        fd_step: Finite-difference step size (default 1e-6).

    Returns:
        Sensitivity Δθ (positive float).

    Raises:
        RuntimeError: If derivative is zero (operating at fringe extremum).
    """
    Jz_S = ops["Jz_S"]

    # Evaluate at theta_true
    psi = evolve_full(psi0, T_BS1, T_BS2, T_H, theta_true, alpha, ops)
    _, var = compute_expectation_and_variance(psi, Jz_S)

    # Central finite difference for ∂⟨Jz_S⟩/∂θ
    psi_plus = evolve_full(psi0, T_BS1, T_BS2, T_H, theta_true + fd_step, alpha, ops)
    psi_minus = evolve_full(psi0, T_BS1, T_BS2, T_H, theta_true - fd_step, alpha, ops)
    exp_plus = np.real(psi_plus.conj() @ Jz_S @ psi_plus)
    exp_minus = np.real(psi_minus.conj() @ Jz_S @ psi_minus)
    d_exp = (exp_plus - exp_minus) / (2.0 * fd_step)

    if abs(d_exp) < 1e-15:
        # Derivative is effectively zero → fringe extremum
        return float("inf")

    return float(np.sqrt(var) / abs(d_exp))


# ============================================================================
# Objective Function for Optimisation
# ============================================================================


def _params_to_components(
    params: np.ndarray,
) -> tuple[
    float, float, float, float, float, float, float, tuple[float, float, float, float]
]:
    """Unpack the 11-element parameter vector into named components.

    Parameter order:
        [θ_S, φ_S, θ_A, φ_A, T_BS1, T_BS2, T_H, α_xx, α_xz, α_zx, α_zz]

    Args:
        params: 11-element array of optimisation parameters.

    Returns:
        Tuple (theta_S, phi_S, theta_A, phi_A, T_BS1, T_BS2, T_H, alpha).
    """
    theta_S = float(params[0])
    phi_S = float(params[1])
    theta_A = float(params[2])
    phi_A = float(params[3])
    T_BS1 = float(params[4])
    T_BS2 = float(params[5])
    T_H = float(params[6])
    alpha: tuple[float, float, float, float] = (
        float(params[7]),
        float(params[8]),
        float(params[9]),
        float(params[10]),
    )
    return theta_S, phi_S, theta_A, phi_A, T_BS1, T_BS2, T_H, alpha


def sensitivity_objective(
    params: np.ndarray,
    theta_true: float,
    ops: dict[str, np.ndarray],
    fd_step: float = 1e-6,
    bounds: dict[str, tuple[float, float]] | None = None,
    penalty_scale: float = 1e6,
) -> float:
    """Objective function for minimising Δθ.

    Args:
        params: 11-element optimisation parameter vector.
        theta_true: True phase rate parameter.
        ops: Two-qubit operators.
        fd_step: Finite-difference step size.
        bounds: Dict of parameter bounds (defaults to article values).
        penalty_scale: Scale for bound-violation penalty.

    Returns:
        Δθ value (plus infinite penalty if bounds violated).
    """
    # Default bounds from the article
    if bounds is None:
        bounds = get_default_bounds()

    theta_S, phi_S, theta_A, phi_A, T_BS1, T_BS2, T_H, alpha = _params_to_components(
        params
    )

    # --- Bound enforcement (penalty method) ---
    penalty = 0.0
    for val, key in [
        (theta_S, "theta"),
        (theta_A, "theta"),
        (phi_S, "phi"),
        (phi_A, "phi"),
        (T_BS1, "T_BS"),
        (T_BS2, "T_BS"),
        (T_H, "T_H"),
    ]:
        lo, hi = bounds[key]
        if val < lo:
            penalty += penalty_scale * (lo - val) ** 2
        if val > hi:
            penalty += penalty_scale * (val - hi) ** 2
    for i in range(4):
        lo, hi = bounds["alpha"]
        if alpha[i] < lo:
            penalty += penalty_scale * (lo - alpha[i]) ** 2
        if alpha[i] > hi:
            penalty += penalty_scale * (alpha[i] - hi) ** 2

    if penalty > 0.0:
        return float(1e10 + penalty)

    # Build initial state
    psi0 = two_qubit_state(theta_S, phi_S, theta_A, phi_A)

    # Compute sensitivity
    dtheta = compute_sensitivity(
        psi0, T_BS1, T_BS2, T_H, theta_true, alpha, ops, fd_step
    )
    return dtheta


# ============================================================================
# Nelder–Mead Optimisation
# ============================================================================


@dataclass
class OptimisationResult:
    """Result of a single Nelder–Mead run.

    Attributes:
        delta_theta_opt: Best sensitivity Δθ found.
        params_opt: Optimal 11-element parameter vector.
        theta_true: True θ used for this optimisation.
        success: Whether the optimiser reported success.
        nfev: Number of function evaluations.
        message: Optimiser message.
        expectation_Jz: ⟨J_z^S⟩ at the optimal operating point.
        variance_Jz: Var(J_z^S) at the optimal operating point.
        purity_S: Tr(ρ_S²) purity of the reduced system state (1 = pure,
            0.5 = maximally entangled with ancilla).
        history: Objective function values at each iteration (for
            convergence analysis). Empty list if callback not enabled.
    """

    delta_theta_opt: float
    params_opt: np.ndarray
    theta_true: float
    success: bool
    nfev: int
    message: str
    expectation_Jz: float = 0.0
    variance_Jz: float = 0.0
    purity_S: float = 0.0
    history: list[float] = field(default_factory=list)


@dataclass
class ThetaScanResult:
    """Results of a θ scan with multiple Nelder–Mead restarts per θ.

    Attributes:
        results: List of OptimisationResult per θ value.
        theta_values: Array of θ values scanned.
        best_per_theta: Best Δθ for each θ value.
        all_results: All results (including non-best restarts) keyed by θ.
    """

    results: list[OptimisationResult] = field(default_factory=list)
    theta_values: np.ndarray = field(default_factory=lambda: np.array([]))
    best_per_theta: np.ndarray = field(default_factory=lambda: np.array([]))
    all_results: dict[float, list[OptimisationResult]] = field(default_factory=dict)


def get_default_bounds() -> dict[str, tuple[float, float]]:
    """Get the default parameter bounds.

    Returns:
        Dict with keys 'theta', 'phi', 'T_BS', 'T_H', 'alpha' mapping to
        (min, max) tuples.
    """
    return {
        "theta": (0.0, np.pi),
        "phi": (0.0, 2.0 * np.pi),
        "T_BS": (0.0, np.pi),
        "T_H": (0.0, 5.0),
        "alpha": (-2.0, 2.0),
    }


def random_initial_params(
    rng: np.random.Generator, bounds: dict[str, tuple[float, float]] | None = None
) -> np.ndarray:
    """Generate random initial parameters within the search bounds.

    All 11 parameters are drawn independently from their respective bounds.

    Args:
        rng: Random number generator.
        bounds: Optional custom bounds (uses defaults if None).

    Returns:
        11-element array of initial parameters.
    """
    if bounds is None:
        bounds = get_default_bounds()

    theta_lo, theta_hi = bounds["theta"]
    phi_lo, phi_hi = bounds["phi"]
    tbs_lo, tbs_hi = bounds["T_BS"]
    th_lo, th_hi = bounds["T_H"]
    alpha_lo, alpha_hi = bounds["alpha"]

    theta_S, theta_A = rng.uniform(theta_lo, theta_hi, size=2)
    phi_S, phi_A = rng.uniform(phi_lo, phi_hi, size=2)
    T_BS1, T_BS2 = rng.uniform(tbs_lo, tbs_hi, size=2)
    T_H = rng.uniform(th_lo, th_hi)
    alpha = rng.uniform(alpha_lo, alpha_hi, size=4)
    return np.array(
        [theta_S, phi_S, theta_A, phi_A, T_BS1, T_BS2, T_H, *alpha], dtype=float
    )


def run_optimisation(
    theta_true: float,
    ops: dict[str, np.ndarray],
    x0: np.ndarray | None = None,
    seed: int | None = None,
    maxiter: int = 5000,
    xatol: float = 1e-8,
    fatol: float = 1e-8,
    adaptive: bool = True,
    bounds: dict[str, tuple[float, float]] | None = None,
    track_history: bool = False,
) -> OptimisationResult:
    """Run a single Nelder–Mead optimisation for ancilla-assisted metrology.

    Args:
        theta_true: True phase rate parameter.
        ops: Two-qubit operators.
        x0: Initial parameter vector (11 elements). Random if None.
        seed: Random seed (used if x0 is None).
        maxiter: Maximum Nelder–Mead iterations.
        xatol: Absolute parameter tolerance.
        fatol: Absolute function tolerance.
        adaptive: Use adaptive Nelder–Mead parameters.
        bounds: Custom parameter bounds dictionary. Uses defaults if None.
        track_history: If True, record objective function values at each
            iteration in the result's `history` field.

    Returns:
        OptimisationResult with the best parameters found.
    """
    return _run_nelder_mead(
        theta_true=theta_true,
        ops=ops,
        x0=x0,
        seed=seed,
        maxiter=maxiter,
        xatol=xatol,
        fatol=fatol,
        adaptive=adaptive,
        bounds=bounds,
        track_history=track_history,
    )


def _run_nelder_mead(
    theta_true: float,
    ops: dict[str, np.ndarray],
    x0: np.ndarray | None = None,
    seed: int | None = None,
    maxiter: int = 5000,
    xatol: float = 1e-8,
    fatol: float = 1e-8,
    adaptive: bool = True,
    bounds: dict[str, tuple[float, float]] | None = None,
    track_history: bool = False,
) -> OptimisationResult:
    """Internal Nelder–Mead runner. Shared by run_optimisation and run_theta_scan.

    Args:
        theta_true: True phase rate parameter.
        ops: Two-qubit operators.
        x0: Initial parameter vector (11 elements). Random if None.
        seed: Random seed (used if x0 is None).
        maxiter: Maximum Nelder–Mead iterations.
        xatol: Absolute parameter tolerance.
        fatol: Absolute function tolerance.
        adaptive: Use adaptive Nelder–Mead parameters.
        bounds: Custom parameter bounds dictionary. Uses defaults if None.
        track_history: If True, record objective function values per iteration.
    """
    if x0 is None:
        rng = np.random.default_rng(seed)
        x0 = random_initial_params(rng, bounds)
    else:
        x0 = np.asarray(x0, dtype=float)
        assert x0.shape == (11,), "x0 must have 11 elements"

    # Objective function (closure over theta_true, ops, bounds)
    def objective(p: np.ndarray) -> float:
        return sensitivity_objective(p, theta_true, ops, bounds=bounds)

    # History tracking via callback
    history: list[float] = []

    def callback(_x: np.ndarray) -> None:
        if track_history:
            val = objective(_x)
            history.append(val)

    result = minimize(
        objective,
        x0=x0,
        method="Nelder-Mead",
        callback=callback if track_history else None,
        options={  # type: ignore[call-overload]
            "maxiter": maxiter,
            "xatol": xatol,
            "fatol": fatol,
            "adaptive": adaptive,
        },
    )

    # Compute expectation, variance, and purity at the optimal point
    opt_params = result.x.copy()
    (
        opt_theta_S,
        opt_phi_S,
        opt_theta_A,
        opt_phi_A,
        opt_T_BS1,
        opt_T_BS2,
        opt_T_H,
        opt_alpha,
    ) = _params_to_components(opt_params)
    opt_psi0 = two_qubit_state(opt_theta_S, opt_phi_S, opt_theta_A, opt_phi_A)
    opt_psi = evolve_full(
        opt_psi0, opt_T_BS1, opt_T_BS2, opt_T_H, theta_true, opt_alpha, ops
    )
    exp_val, var_val = compute_expectation_and_variance(opt_psi, ops["Jz_S"])
    purity = compute_reduced_purity(opt_psi)

    return OptimisationResult(
        delta_theta_opt=float(result.fun),
        params_opt=opt_params,
        theta_true=theta_true,
        success=bool(result.success),
        nfev=int(result.nfev),
        message=str(result.message),
        expectation_Jz=exp_val,
        variance_Jz=var_val,
        purity_S=purity,
        history=history.copy(),
    )


def run_theta_scan(
    theta_values: list[float] | np.ndarray,
    n_restarts: int = 10,
    seed: int | None = 42,
    maxiter: int = 5000,
    xatol: float = 1e-8,
    fatol: float = 1e-8,
    adaptive: bool = True,
    bounds: dict[str, tuple[float, float]] | None = None,
    track_history: bool = False,
) -> ThetaScanResult:
    """Scan over θ values with multiple Nelder–Mead restarts each.

    Args:
        theta_values: θ values to scan.
        n_restarts: Number of random-start Nelder–Mead runs per θ.
        seed: Base random seed (incremented per restart).
        maxiter: Maximum Nelder–Mead iterations per run.
        xatol: Absolute parameter tolerance.
        fatol: Absolute function tolerance.
        adaptive: Use adaptive Nelder–Mead parameters.
        bounds: Custom parameter bounds (e.g., to expand T_H range).
            Default: T_H ∈ [0, 5]. Use bounds={"T_H": (0, 20), ...} for
            expanded-range experiments.
        track_history: If True, record convergence history per run.

    Returns:
        ThetaScanResult with all recorded information.
    """
    ops = build_two_qubit_operators()
    theta_arr = np.asarray(theta_values, dtype=float)
    base_seed = seed if seed is not None else 42

    all_results: dict[float, list[OptimisationResult]] = {}
    best_per_theta_list: list[float] = []
    all_results_flat: list[OptimisationResult] = []

    for theta in theta_arr:
        theta_results: list[OptimisationResult] = []
        for restart in range(n_restarts):
            rng = np.random.default_rng(base_seed + int(theta * 1000) + restart)
            x0 = random_initial_params(rng, bounds)
            opt_result = _run_nelder_mead(
                theta_true=theta,
                ops=ops,
                x0=x0,
                maxiter=maxiter,
                xatol=xatol,
                fatol=fatol,
                adaptive=adaptive,
                bounds=bounds,
                track_history=track_history,
            )
            theta_results.append(opt_result)
            all_results_flat.append(opt_result)

        # Sort by sensitivity (ascending)
        theta_results.sort(key=lambda r: r.delta_theta_opt)
        all_results[theta] = theta_results
        best_per_theta_list.append(theta_results[0].delta_theta_opt)

    return ThetaScanResult(
        results=all_results_flat,
        theta_values=theta_arr,
        best_per_theta=np.array(best_per_theta_list),
        all_results=all_results,
    )


# ============================================================================
# Validation Helpers
# ============================================================================


def validate_operators(ops: dict[str, np.ndarray]) -> bool:
    """Validate all two-qubit operators.

    Checks: Hermiticity, commutation relations.

    Args:
        ops: Two-qubit operators.

    Returns:
        True if all checks pass.

    Raises:
        AssertionError: If any check fails.
    """
    for name, op in ops.items():
        assert op.shape == (4, 4), f"{name} must be 4×4, got {op.shape}"
        assert np.allclose(op, op.conj().T, atol=1e-12), f"{name} must be Hermitian"

    # Commutation: [J_z^S, J_x^S] = i J_y^S
    comm_zx_S = ops["Jz_S"] @ ops["Jx_S"] - ops["Jx_S"] @ ops["Jz_S"]
    assert np.allclose(comm_zx_S, 1j * ops["Jy_S"], atol=1e-12), (
        "[Jz_S, Jx_S] = i Jy_S failed"
    )

    # Commutation: [J_z^A, J_x^A] = i J_y^A
    comm_zx_A = ops["Jz_A"] @ ops["Jx_A"] - ops["Jx_A"] @ ops["Jz_A"]
    assert np.allclose(comm_zx_A, 1j * ops["Jy_A"], atol=1e-12), (
        "[Jz_A, Jx_A] = i Jy_A failed"
    )

    return True


def validate_bs_unitarity(T: float = np.pi / 4) -> bool:
    """Validate the beam-splitter unitary.

    Args:
        T: Beam-splitter duration.

    Returns:
        True if unitary.
    """
    U = bs_unitary(T)
    assert np.allclose(U @ U.conj().T, I_2, atol=1e-12), "BS must be unitary"
    assert np.allclose(U.conj().T @ U, I_2, atol=1e-12), "BS† must be unitary"
    return True


def validate_two_qubit_bs_unitarity(T: float = np.pi / 4) -> bool:
    """Validate the two-qubit beam-splitter unitary.

    Args:
        T: Beam-splitter duration.

    Returns:
        True if unitary.
    """
    U = two_qubit_bs_unitary(T)
    I_4 = np.eye(4, dtype=complex)
    assert np.allclose(U @ U.conj().T, I_4, atol=1e-12), "2-qubit BS must be unitary"
    return True


def validate_hold_unitarity(
    T_H: float = 1.0,
    theta: float = 1.0,
    alpha: tuple[float, float, float, float] = (0.1, 0.0, 0.0, 0.0),
) -> bool:
    """Validate the hold unitary.

    Args:
        T_H: Holding time.
        theta: Phase rate.
        alpha: Interaction coefficients.

    Returns:
        True if unitary.
    """
    ops = build_two_qubit_operators()
    U = hold_unitary(T_H, theta, alpha, ops)
    I_4 = np.eye(4, dtype=complex)
    assert np.allclose(U @ U.conj().T, I_4, atol=1e-12), "Hold must be unitary"
    return True


def validate_sensitivity_reasonable(
    T_H_vals: list[float] | None = None,
) -> bool:
    """Verify that sensitivity Δθ ≈ 1/T_H in the decoupled (α=0) case.

    Checks that the analytically optimal configuration achieves Δθ ≈ 1/T_H
    when the interaction is off.

    Args:
        T_H_vals: Holding-time values to check.

    Returns:
        True if all checks pass.
    """
    if T_H_vals is None:
        T_H_vals = [0.5, 1.0, 2.0]

    ops = build_two_qubit_operators()

    # Analytic optimum for decoupled case:
    # |ψ_S⟩ = |1,0⟩, 50/50 beam splitters (T = π/2)
    theta_S, phi_S = 0.0, 0.0  # |1,0⟩
    theta_A, phi_A = 0.0, 0.0  # |1,0⟩ (ancilla doesn't matter)
    alpha = (0.0, 0.0, 0.0, 0.0)
    T_BS = np.pi / 2.0

    psi0 = two_qubit_state(theta_S, phi_S, theta_A, phi_A)

    for T_H in T_H_vals:
        # Use θ_true = 1.0 (away from fringe extremum)
        dtheta = compute_sensitivity(psi0, T_BS, T_BS, T_H, 1.0, alpha, ops)
        expected = 1.0 / T_H
        # Relative tolerance 5% to account for finite-difference and
        # residual fringe effects
        assert np.isclose(dtheta, expected, rtol=0.05), (
            f"Δθ = {dtheta:.6f} for T_H={T_H}, expected ≈ {expected:.6f}"
        )

    return True


def validate_variance_positive(
    psi: np.ndarray,
    operator: np.ndarray,
    atol: float = 1e-12,
) -> bool:
    """Validate that Var(O) ≥ -atol for a given state and operator.

    A slightly negative variance (order 1e-16) can arise from numerical
    rounding; this function asserts it is not significantly negative.

    Args:
        psi: Normalised state vector.
        operator: Hermitian operator matrix.
        atol: Absolute tolerance for negative variance (default 1e-12).

    Returns:
        True if check passes.

    Raises:
        AssertionError: If variance < -atol (unphysical).
    """
    _, var = compute_expectation_and_variance(psi, operator)
    assert var >= -atol, f"Unphysical negative variance: Var = {var:.2e}"
    return True


def validate_derivative_stability(
    psi0: np.ndarray,
    T_BS1: float,
    T_BS2: float,
    T_H: float,
    theta_true: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
    fd_steps: tuple[float, float, float] = (1e-5, 1e-6, 1e-7),
    rtol: float = 0.02,
) -> bool:
    """Check that the finite-difference derivative is stable w.r.t. step size.

    Computes Δθ at multiple fd_step values and asserts the relative spread
    is below `rtol`.  This validates that the default fd_step = 1e-6 is not
    in a noisy regime.

    Args:
        psi0: Initial 4-vector (product state).
        T_BS1: First beam-splitter duration.
        T_BS2: Second beam-splitter duration.
        T_H: Holding-time strength.
        theta_true: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators (must contain 'Jz_S').
        fd_steps: Three fd_step values to compare (default 1e-5, 1e-6, 1e-7).
        rtol: Maximum allowed relative spread (default 0.02 = 2%).

    Returns:
        True if all checks pass.

    Raises:
        AssertionError: If derivative is unstable across step sizes.
    """
    sensitivities: list[float] = []
    for step in fd_steps:
        dtheta = compute_sensitivity(
            psi0, T_BS1, T_BS2, T_H, theta_true, alpha, ops, fd_step=step
        )
        if not np.isfinite(dtheta):
            # Skip fringe-extremum configurations
            continue
        sensitivities.append(dtheta)

    if len(sensitivities) < 2:
        # Not enough finite values to compare — skip (likely at fringe extremum)
        return True

    arr = np.array(sensitivities)
    mean_val = float(np.mean(arr))
    if mean_val == 0.0:
        return True

    # Max relative deviation from the mean
    max_dev = float(np.max(np.abs(arr - mean_val) / mean_val))
    assert max_dev < rtol, (
        f"Derivative unstable across fd_steps {fd_steps}: "
        f"sensitivities = {sensitivities}, max relative deviation = {max_dev:.4f}"
    )
    return True


# ============================================================================
# Convenience Runner
# ============================================================================


def compute_convergence_metric(
    results: list[OptimisationResult],
) -> float:
    """Compute the convergence spread metric for a set of restarts.

    Returns std(Δθ) / mean(Δθ) for the given results. A value < 0.10
    indicates consistent convergence across restarts (Success Criterion #1).

    Args:
        results: List of OptimisationResult for a given θ (all restarts).

    Returns:
        Relative standard deviation (spread / mean). Returns 0.0 if
        fewer than 2 results are provided or mean is zero.
    """
    if len(results) < 2:
        return 0.0
    deltas = np.array([r.delta_theta_opt for r in results])
    # Filter out infinite values (fringe-extremum results)
    finite = deltas[np.isfinite(deltas)]
    if len(finite) < 2:
        return 0.0
    mean_val = float(np.mean(finite))
    if mean_val == 0.0:
        return 0.0
    return float(np.std(finite, ddof=1) / mean_val)


def get_decoupled_sensitivity(T_H: float, theta_true: float = 1.0) -> float:
    """Compute the SQL sensitivity for the decoupled (α=0) case.

    Optimal configuration: system in |1,0⟩, 50/50 beam splitters, no interaction.

    Args:
        T_H: Holding-time strength.
        theta_true: True phase rate.

    Returns:
        Δθ (ideally = 1/T_H).
    """
    ops = build_two_qubit_operators()
    psi0 = two_qubit_state(0.0, 0.0, 0.0, 0.0)  # both in |1,0⟩
    T_BS = np.pi / 2.0
    alpha = (0.0, 0.0, 0.0, 0.0)
    return compute_sensitivity(psi0, T_BS, T_BS, T_H, theta_true, alpha, ops)


# ============================================================================
# α-Coefficient Scans (Grid and Random Search)
# ============================================================================


@dataclass
class AlphaSingleScanResult:
    """Result from scanning a single α coefficient while holding others fixed.

    Attributes:
        alpha_name: Which coefficient was scanned ('xx', 'xz', 'zx', 'zz').
        alpha_values: Array of α values scanned.
        delta_theta_values: Corresponding Δθ sensitivity values.
        fixed_params: Dict of the other fixed parameters used.
    """

    alpha_name: str
    alpha_values: np.ndarray
    delta_theta_values: np.ndarray
    fixed_params: dict[str, float] = field(default_factory=dict)


@dataclass
class AlphaRandomSearchResult:
    """Result from random search over the 4D α coefficient space.

    Attributes:
        alpha_samples: Array of shape (N, 4) with sampled α values.
        delta_theta_values: Array of shape (N,) with Δθ for each sample.
        best_alpha: The α = (α_xx, α_xz, α_zx, α_zz) that gave minimal Δθ.
        best_delta_theta: The minimal Δθ found.
        fixed_params: Dict of the other fixed parameters used.
    """

    alpha_samples: np.ndarray
    delta_theta_values: np.ndarray
    best_alpha: tuple[float, float, float, float]
    best_delta_theta: float
    fixed_params: dict[str, float] = field(default_factory=dict)


def scan_alpha_single_parameter(
    alpha_name: str,
    alpha_min: float = -2.0,
    alpha_max: float = 2.0,
    n_points: int = 21,
    *,
    theta_S: float = np.pi / 2,
    phi_S: float = 0.0,
    theta_A: float = 0.0,
    phi_A: float = 0.0,
    T_BS1: float = np.pi / 2,
    T_BS2: float = np.pi / 2,
    T_H: float = 1.0,
    theta_true: float = 1.0,
) -> AlphaSingleScanResult:
    """Scan a single α coefficient while holding others fixed.

    This replicates the grid scan described in the article: "each α_ij is
    scanned independently in [-2, 2] with 21 points, while the other three
    are held at zero."

    Physical configuration defaults (SQL-optimal for α=0):
        - System: |ψ_S⟩ = (|0⟩ + |1⟩)/√2 (θ_S = π/2)
        - Ancilla: |ψ_A⟩ = |0⟩ (θ_A = 0)
        - Beam splitters: 50/50 (T_BS1 = T_BS2 = π/2)
        - T_H = 1.0, θ_true = 1.0

    Args:
        alpha_name: Which coefficient to scan: 'xx', 'xz', 'zx', or 'zz'.
        alpha_min: Minimum value for the scan (default -2.0).
        alpha_max: Maximum value for the scan (default 2.0).
        n_points: Number of points in the scan (default 21).
        theta_S: System polar angle (default π/2).
        phi_S: System azimuthal angle (default 0.0).
        theta_A: Ancilla polar angle (default 0.0).
        phi_A: Ancilla azimuthal angle (default 0.0).
        T_BS1: First beam-splitter duration (default π/2).
        T_BS2: Second beam-splitter duration (default π/2).
        T_H: Holding time (default 1.0).
        theta_true: True phase rate (default 1.0).

    Returns:
        AlphaSingleScanResult with scanned values and sensitivities.

    Raises:
        ValueError: If alpha_name is not one of 'xx', 'xz', 'zx', 'zz'.
    """
    alpha_idx_map = {"xx": 0, "xz": 1, "zx": 2, "zz": 3}
    if alpha_name not in alpha_idx_map:
        raise ValueError(
            f"alpha_name must be one of {list(alpha_idx_map.keys())}, got {alpha_name}"
        )
    scan_idx = alpha_idx_map[alpha_name]

    ops = build_two_qubit_operators()
    psi0 = two_qubit_state(theta_S, phi_S, theta_A, phi_A)

    alpha_values = np.linspace(alpha_min, alpha_max, n_points)
    delta_theta_values = np.zeros(n_points, dtype=float)

    for i, a_val in enumerate(alpha_values):
        alpha_list = [0.0, 0.0, 0.0, 0.0]
        alpha_list[scan_idx] = a_val
        alpha: tuple[float, float, float, float] = (
            alpha_list[0],
            alpha_list[1],
            alpha_list[2],
            alpha_list[3],
        )
        dtheta = compute_sensitivity(psi0, T_BS1, T_BS2, T_H, theta_true, alpha, ops)
        delta_theta_values[i] = dtheta

    fixed_params = {
        "theta_S": theta_S,
        "phi_S": phi_S,
        "theta_A": theta_A,
        "phi_A": phi_A,
        "T_BS1": T_BS1,
        "T_BS2": T_BS2,
        "T_H": T_H,
        "theta_true": theta_true,
    }

    return AlphaSingleScanResult(
        alpha_name=alpha_name,
        alpha_values=alpha_values,
        delta_theta_values=delta_theta_values,
        fixed_params=fixed_params,
    )


def random_search_alpha(
    n_samples: int = 200,
    alpha_min: float = -2.0,
    alpha_max: float = 2.0,
    *,
    theta_S: float = np.pi / 2,
    phi_S: float = 0.0,
    theta_A: float = 0.0,
    phi_A: float = 0.0,
    T_BS1: float = np.pi / 2,
    T_BS2: float = np.pi / 2,
    T_H: float = 1.0,
    theta_true: float = 1.0,
    seed: int | None = 42,
) -> AlphaRandomSearchResult:
    """Random search over the 4D α = (α_xx, α_xz, α_zx, α_zz) space.

    This replicates the random search described in the article: "200 samples
    over the full 4D α space" to verify that no combination achieves
    Δθ < 1/T_H (SQL).

    Args:
        n_samples: Number of random α samples to evaluate (default 200).
        alpha_min: Lower bound for all α coefficients (default -2.0).
        alpha_max: Upper bound for all α coefficients (default 2.0).
        theta_S: System polar angle (default π/2).
        phi_S: System azimuthal angle (default 0.0).
        theta_A: Ancilla polar angle (default 0.0).
        phi_A: Ancilla azimuthal angle (default 0.0).
        T_BS1: First beam-splitter duration (default π/2).
        T_BS2: Second beam-splitter duration (default π/2).
        T_H: Holding time (default 1.0).
        theta_true: True phase rate (default 1.0).
        seed: Random seed for reproducibility (default 42).

    Returns:
        AlphaRandomSearchResult with all samples and the best found.
    """
    rng = np.random.default_rng(seed)
    ops = build_two_qubit_operators()
    psi0 = two_qubit_state(theta_S, phi_S, theta_A, phi_A)

    # Sample uniformly in [alpha_min, alpha_max]^4
    alpha_samples = rng.uniform(alpha_min, alpha_max, size=(n_samples, 4))
    delta_theta_values = np.zeros(n_samples, dtype=float)

    for i in range(n_samples):
        alpha: tuple[float, float, float, float] = (
            float(alpha_samples[i, 0]),
            float(alpha_samples[i, 1]),
            float(alpha_samples[i, 2]),
            float(alpha_samples[i, 3]),
        )
        dtheta = compute_sensitivity(psi0, T_BS1, T_BS2, T_H, theta_true, alpha, ops)
        delta_theta_values[i] = dtheta

    # Find best (minimal Δθ)
    best_idx = int(np.argmin(delta_theta_values))
    best_alpha: tuple[float, float, float, float] = (
        float(alpha_samples[best_idx, 0]),
        float(alpha_samples[best_idx, 1]),
        float(alpha_samples[best_idx, 2]),
        float(alpha_samples[best_idx, 3]),
    )
    best_delta_theta = float(delta_theta_values[best_idx])

    fixed_params = {
        "theta_S": theta_S,
        "phi_S": phi_S,
        "theta_A": theta_A,
        "phi_A": phi_A,
        "T_BS1": T_BS1,
        "T_BS2": T_BS2,
        "T_H": T_H,
        "theta_true": theta_true,
    }

    return AlphaRandomSearchResult(
        alpha_samples=alpha_samples,
        delta_theta_values=delta_theta_values,
        best_alpha=best_alpha,
        best_delta_theta=best_delta_theta,
        fixed_params=fixed_params,
    )
