"""
Ancilla-Assisted Metrology Optimization via Nelder–Mead.

Implements the full-parameter optimisation of a two-qubit (system + ancilla)
Mach–Zehnder interferometer for estimating an unknown phase rate ω.

Physical Model:
- Two qubits: system (S) and ancilla (A), each isomorphic to a spin-½.
- Basis: {|1,0⟩, |0,1⟩} for each qubit (single-particle subspace).
- Beam splitters: generated by J_x with optimisable duration T.
- Holding Hamiltonian:
    H_hold = ω J_z^S + H_int(α)
    H_int = α_xx J_x^S⊗J_x^A + α_xz J_x^S⊗J_z^A + α_zx J_z^S⊗J_x^A + α_zz J_z^S⊗J_z^A
- Measurement: J_z^S on the system qubit.
- Sensitivity: Δω via error propagation (central finite differences).

Units:
- Dimensionless throughout. ω is the unknown phase rate (radians per unit time).
- t_hold: holding-time strength (dimensionless).
- α coefficients: real coupling strengths.

References:
- Giovannetti, Lloyd, Maccone, Nat. Photonics 5, 222 (2011)
- Davis et al., PRA 94, 063814 (2016)
- Kitagawa & Ueda, PRA 47, 5138 (1993)
- Hentschel & Sanders, PRA 88, 062329 (2013)

"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import ClassVar

import numpy as np
import pandas as pd
from scipy.linalg import expm
from scipy.optimize import minimize

from src.utils.constants import I_2, I_4, J_X, J_Y, J_Z, SIGMA_X, SIGMA_Z

# ============================================================================
# Operator Construction
# ============================================================================


def build_two_qubit_operators() -> dict[str, np.ndarray]:
    """Build the 4×4 operators for the two-qubit system.

    Basis ordering (computational basis):
        |0⟩_S|0⟩_A, |0⟩_S|1⟩_A, |1⟩_S|0⟩_A, |1⟩_S|1⟩_A
    where |0⟩ = |1,0⟩ (particle in mode 0), |1⟩ = |0,1⟩ (particle in mode 1).

    Returns:
        Dict with keys 'Jz_S', 'Jz_A', 'Jx_S', 'Jx_A', 'Jy_S', 'Jy_A',
        each a 4×4 complex Hermitian matrix.

    """
    return {
        "Jz_S": np.kron(J_Z, I_2),
        "Jz_A": np.kron(I_2, J_Z),
        "Jx_S": np.kron(J_X, I_2),
        "Jx_A": np.kron(I_2, J_X),
        "Jy_S": np.kron(J_Y, I_2),
        "Jy_A": np.kron(I_2, J_Y),
    }


def build_interaction_hamiltonian(
    alpha: tuple[float, float, float, float],
) -> np.ndarray:
    """Build the system–ancilla interaction Hamiltonian.

    H_int = α_xx · J_x^S ⊗ J_x^A + α_xz · J_x^S ⊗ J_z^A
          + α_zx · J_z^S ⊗ J_x^A + α_zz · J_z^S ⊗ J_z^A

    Args:
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.

    Returns:
        4×4 Hermitian interaction matrix.

    """
    a_xx, a_xz, a_zx, a_zz = alpha

    # Tensor-product operators: J_i^S ⊗ J_j^A  =  (σ_i/2) ⊗ (σ_j/2) = σ_i ⊗ σ_j / 4
    # Pre-compute the four tensor products
    xx = np.kron(SIGMA_X / 2, SIGMA_X / 2)  # J_x^S ⊗ J_x^A
    xz = np.kron(SIGMA_X / 2, SIGMA_Z / 2)  # J_x^S ⊗ J_z^A
    zx = np.kron(SIGMA_Z / 2, SIGMA_X / 2)  # J_z^S ⊗ J_x^A
    zz = np.kron(SIGMA_Z / 2, SIGMA_Z / 2)  # J_z^S ⊗ J_z^A

    H = np.zeros((4, 4), dtype=complex)
    if a_xx != 0.0:
        H += a_xx * xx
    if a_xz != 0.0:
        H += a_xz * xz
    if a_zx != 0.0:
        H += a_zx * zx
    if a_zz != 0.0:
        H += a_zz * zz
    return H


# ============================================================================
# State Preparation
# ============================================================================


def single_qubit_state(theta: float, phi_Bloch: float) -> np.ndarray:
    """Create a single-qubit pure state on the Bloch sphere.

    |ψ⟩ = cos(θ/2) |0⟩ + e^{iφ} sin(θ/2) |1⟩

    where |0⟩ = |1,0⟩ (particle in mode 0), |1⟩ = |0,1⟩ (particle in mode 1).

    Args:
        theta: Polar angle ∈ [0, π].
        phi_Bloch: Azimuthal angle ∈ [0, 2π).

    Returns:
        Normalised complex 2-vector.

    """
    return np.array(
        [np.cos(theta / 2.0), np.exp(1j * phi_Bloch) * np.sin(theta / 2.0)],
        dtype=complex,
    )


def two_qubit_state(
    theta_S: float,
    phi_S: float,
    theta_A: float,
    phi_A: float,
) -> np.ndarray:
    """Create a product state |ψ_S⟩ ⊗ |ψ_A⟩.

    Args:
        theta_S: Polar angle for system qubit.
        phi_S: Azimuthal angle for system qubit.
        theta_A: Polar angle for ancilla qubit.
        phi_A: Azimuthal angle for ancilla qubit.

    Returns:
        Normalised complex 4-vector (product state).

    """
    psi_S = single_qubit_state(theta_S, phi_S)
    psi_A = single_qubit_state(theta_A, phi_A)
    return np.kron(psi_S, psi_A)


def free_ancilla_initial_state(theta_A: float, phi_A: float) -> np.ndarray:
    r"""Construct the system--ancilla product initial state.

    :math:`|\Psi_0\rangle = |1,0\rangle_S \otimes |\psi_A(\theta_A, \phi_A)\rangle`

    where :math:`|\psi_A\rangle = \cos(\theta_A/2)\,|1,0\rangle_A
    + e^{i\phi_A}\sin(\theta_A/2)\,|0,1\rangle_A`.

    Args:
        theta_A: Ancilla polar angle :math:`\in [0, \pi]`.
        phi_A: Ancilla azimuthal angle :math:`\in [0, 2\pi)`.

    Returns:
        Normalised 4-vector in the :math:`\{|00\rangle, |01\rangle, |10\rangle,
        |11\rangle\}` basis.
    """
    psi_S = np.array([1.0, 0.0], dtype=complex)  # |1,0⟩_S
    psi_A = single_qubit_state(theta_A, phi_A)
    state = np.kron(psi_S, psi_A)
    assert np.isclose(np.linalg.norm(state), 1.0), (
        "Free-ancilla initial state must be normalised"
    )
    return state


# ============================================================================
# Beam-Splitter Unitaries
# ============================================================================


def bs_unitary(T_BS: float) -> np.ndarray:
    """Single-qubit beam-splitter unitary generated by J_x.

    U_BS(T_BS) = exp(-i T_BS J_x) = cos(T_BS/2) I - i sin(T_BS/2) σ_x

    A 50/50 beam splitter corresponds to T_BS = π/2.

    Args:
        T_BS: Beam-splitter duration (optimisable parameter).

    Returns:
        2×2 unitary matrix.

    """
    from src.physics.beam_splitter import bs_qubit  # fmt: skip

    return bs_qubit(T_BS)


def two_qubit_bs_unitary(T_BS: float) -> np.ndarray:
    """Two-qubit beam-splitter unitary: U_BS(T_BS) ⊗ U_BS(T_BS).

    Args:
        T_BS: Beam-splitter duration.

    Returns:
        4×4 unitary matrix (tensor product).

    """
    return np.kron(bs_unitary(T_BS), bs_unitary(T_BS))


# ============================================================================
# Holding Hamiltonian & Unitary
# ============================================================================


def build_hold_hamiltonian(
    omega: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
) -> np.ndarray:
    """Build the full holding Hamiltonian.

    H_hold = ω J_z^S + H_int(α)

    Args:
        omega: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators from build_two_qubit_operators().

    Returns:
        4×4 Hermitian Hamiltonian matrix.

    """
    H_int = build_interaction_hamiltonian(alpha)
    H = omega * ops["Jz_S"] + H_int
    # Ensure Hermiticity
    return 0.5 * (H + H.conj().T)


def hold_unitary_two_qubit(
    t_hold: float,
    omega: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
) -> np.ndarray:
    """Holding-time unitary for the 2-qubit ancilla system.

    U_hold(t_hold) = exp(-i t_hold H_hold)

    Args:
        t_hold: Holding-time strength.
        omega: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators from build_two_qubit_operators().

    Returns:
        4×4 unitary matrix.

    """
    H = build_hold_hamiltonian(omega, alpha, ops)
    U = expm(-1j * t_hold * H)
    assert np.allclose(U @ U.conj().T, I_4, atol=1e-12), (
        f"Hold unitary not unitary for t_hold={t_hold}, ω={omega}, α={alpha}"
    )
    return U


# ============================================================================
# Full Circuit Evolution
# ============================================================================


def evolve_full(
    psi0: np.ndarray,
    T_BS1: float,
    T_BS2: float,
    t_hold: float,
    omega: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
) -> np.ndarray:
    """Run the full MZI circuit.

    |ψ_final⟩ = U_BS(T_BS2) · U_hold(t_hold, ω, α) · U_BS(T_BS1) · |ψ₀⟩

    Args:
        psi0: Initial 4-vector (product state).
        T_BS1: First beam-splitter duration.
        T_BS2: Second beam-splitter duration.
        t_hold: Holding-time strength.
        omega: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators.

    Returns:
        Final 4-vector state.

    Raises:
        AssertionError: If input state is not normalised.

    Constraints:
        psi0 must be normalized 4-vector.
        T_BS1, T_BS2, t_hold > 0.
        omega real (phase rate parameter).
        alpha tuple must be length 4: (α_xx, α_xz, α_zx, α_zz).
        ops must contain keys for all required two-qubit operators.

    """
    assert np.isclose(np.linalg.norm(psi0), 1.0), "Initial state must be normalised"

    psi = two_qubit_bs_unitary(T_BS1) @ psi0
    psi = hold_unitary_two_qubit(t_hold, omega, alpha, ops) @ psi
    psi = two_qubit_bs_unitary(T_BS2) @ psi

    assert np.isclose(np.linalg.norm(psi), 1.0), "Final state must be normalised"
    return psi


# ============================================================================
# Sensitivity Computation (Error Propagation)
# ============================================================================


def build_joint_operator(ops: dict[str, np.ndarray]) -> np.ndarray:
    """Build the joint measurement operator M = J_z^S + J_z^A.

    Args:
        ops: Two-qubit operators from build_two_qubit_operators().

    Returns:
        4×4 Hermitian matrix representing the joint measurement.

    """
    return ops["Jz_S"] + ops["Jz_A"]


def compute_covariance(
    psi: np.ndarray,
    ops: dict[str, np.ndarray],
) -> float:
    """Compute Cov(J_z^S, J_z^A) = ⟨J_z^S J_z^A⟩ - ⟨J_z^S⟩⟨J_z^A⟩.

    Args:
        psi: Normalised state vector (4-component).
        ops: Two-qubit operators (must contain 'Jz_S', 'Jz_A').

    Returns:
        Covariance between J_z^S and J_z^A measurements.

    """
    Jz_S = ops["Jz_S"]
    Jz_A = ops["Jz_A"]

    exp_S = np.real(psi.conj() @ Jz_S @ psi)
    exp_A = np.real(psi.conj() @ Jz_A @ psi)
    exp_SA = np.real(psi.conj() @ (Jz_S @ Jz_A) @ psi)

    cov = exp_SA - exp_S * exp_A
    # Covariance can be legitimately negative (anti-correlation).
    # Only check for NaN/Inf and that it lies in the mathematically
    # allowed range: |Cov(X,Y)| ≤ sqrt(Var(X) * Var(Y)).
    assert np.isfinite(cov), f"Covariance is not finite: Cov = {cov}"
    return float(cov)


def compute_expectation_and_variance(
    psi: np.ndarray,
    operator: np.ndarray,
) -> tuple[float, float]:
    """Compute ⟨ψ|O|ψ⟩ and Var(O) = ⟨O²⟩ - ⟨O⟩² for a pure state.

    Args:
        psi: Normalised state vector.
        operator: Hermitian operator matrix.

    Returns:
        Tuple (expectation, variance).

    """
    exp_val = np.real(psi.conj() @ operator @ psi)
    op_sq = operator @ operator
    exp_sq = np.real(psi.conj() @ op_sq @ psi)
    raw_var = exp_sq - exp_val**2
    # Numerical rounding can produce tiny negative variances (~1e-16).
    # Assert that variance is not significantly negative (physics error).
    assert raw_var >= -1e-12, (
        f"Unphysical negative variance: Var = {raw_var:.2e} (expectation = {exp_val:.6f})"
    )
    # Clamp residual round-off noise (typically O(1e-16)) to zero.
    var_val = max(0.0, raw_var)
    return float(exp_val), float(var_val)


def compute_reduced_purity(psi: np.ndarray) -> float:
    """Purity of the reduced density matrix of the system qubit.

    For a two-qubit pure state |ψ⟩ ∈ ℂ⁴ in the basis
    {|00⟩, |01⟩, |10⟩, |11⟩}, the reduced density matrix of the
    system qubit is ρ_S = Tr_A(|ψ⟩⟨ψ|).  Purity = Tr(ρ_S²).

    For a product state, purity = 1.  For a maximally entangled
    Bell state, purity = 0.5.

    Args:
        psi: Normalised 4-vector two-qubit state.

    Returns:
        Purity Tr(ρ_S²) ∈ [0.5, 1.0].

    """
    # psi components: [⟨00|ψ⟩, ⟨01|ψ⟩, ⟨10|ψ⟩, ⟨11|ψ⟩]
    # Reduced density matrix ρ_S = Tr_A(|ψ⟩⟨ψ|):
    #   ρ_S[0,0] = |⟨00|ψ⟩|² + |⟨01|ψ⟩|²   (prob. system in |0⟩)
    #   ρ_S[1,1] = |⟨10|ψ⟩|² + |⟨11|ψ⟩|²   (prob. system in |1⟩)
    #   ρ_S[0,1] = ⟨00|ψ⟩⟨ψ|10⟩ + ⟨01|ψ⟩⟨ψ|11⟩  (coherence)
    rho_00 = abs(psi[0]) ** 2 + abs(psi[1]) ** 2
    rho_11 = abs(psi[2]) ** 2 + abs(psi[3]) ** 2
    rho_01 = psi[0] * np.conj(psi[2]) + psi[1] * np.conj(psi[3])
    purity = rho_00**2 + rho_11**2 + 2.0 * abs(rho_01) ** 2
    # Assert the mathematically expected range [0.5, 1.0].
    # Outside this range indicates a computation error, not numerical noise.
    assert 0.5 - 1e-12 <= purity <= 1.0 + 1e-12, (
        f"Purity {purity:.15f} outside expected range [0.5, 1.0]"
    )
    return float(purity)


def compute_sensitivity(
    psi0: np.ndarray,
    T_BS1: float,
    T_BS2: float,
    t_hold: float,
    omega_true: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
    fd_step: float = 1e-6,
    meas_op: np.ndarray | None = None,
) -> float:
    """Compute the error-propagation sensitivity Δω.

    Δω = sqrt(Var(O)) / |∂⟨O⟩/∂ω|

    where O is the measurement operator (default: J_z^S).

    The derivative is computed via central finite differences.

    Args:
        psi0: Initial 4-vector (product state).
        T_BS1: First beam-splitter duration.
        T_BS2: Second beam-splitter duration.
        t_hold: Holding-time strength.
        omega_true: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators (must contain 'Jz_S').
        fd_step: Finite-difference step size (default 1e-6).
        meas_op: Measurement operator. Defaults to ops['Jz_S'] (S-only).

    Returns:
        Sensitivity Δω (positive float).

    Raises:
        RuntimeError: If derivative is zero (operating at fringe extremum).

    """
    if meas_op is None:
        meas_op = ops["Jz_S"]

    # Evaluate at omega_true
    psi = evolve_full(psi0, T_BS1, T_BS2, t_hold, omega_true, alpha, ops)
    _, var = compute_expectation_and_variance(psi, meas_op)

    # Central finite difference for ∂⟨O⟩/∂θ
    psi_plus = evolve_full(psi0, T_BS1, T_BS2, t_hold, omega_true + fd_step, alpha, ops)
    psi_minus = evolve_full(
        psi0, T_BS1, T_BS2, t_hold, omega_true - fd_step, alpha, ops
    )
    exp_plus = np.real(psi_plus.conj() @ meas_op @ psi_plus)
    exp_minus = np.real(psi_minus.conj() @ meas_op @ psi_minus)
    d_exp = (exp_plus - exp_minus) / (2.0 * fd_step)

    if abs(d_exp) < 1e-12:
        # Derivative is effectively zero → fringe extremum
        return float("inf")

    return float(np.sqrt(var) / abs(d_exp))


# ============================================================================
# Objective Function for Optimisation
# ============================================================================


def _params_to_components(
    params: np.ndarray,
) -> tuple[
    float,
    float,
    float,
    float,
    float,
    float,
    float,
    tuple[float, float, float, float],
]:
    """Unpack the 11-element parameter vector into named components.

    Parameter order:
        [θ_S, φ_S, θ_A, φ_A, T_BS1, T_BS2, t_hold, α_xx, α_xz, α_zx, α_zz]
        Note: θ_S, θ_A are Bloch sphere polar angles, NOT the phase rate ω.

    Args:
        params: 11-element array of optimisation parameters.

    Returns:
        Tuple (theta_S, phi_S, theta_A, phi_A, T_BS1, T_BS2, t_hold, alpha).

    """
    theta_S = float(params[0])
    phi_S = float(params[1])
    theta_A = float(params[2])
    phi_A = float(params[3])
    T_BS1 = float(params[4])
    T_BS2 = float(params[5])
    t_hold = float(params[6])
    alpha: tuple[float, float, float, float] = (
        float(params[7]),
        float(params[8]),
        float(params[9]),
        float(params[10]),
    )
    return theta_S, phi_S, theta_A, phi_A, T_BS1, T_BS2, t_hold, alpha


def sensitivity_objective(
    params: np.ndarray,
    omega_true: float,
    ops: dict[str, np.ndarray],
    fd_step: float = 1e-6,
    bounds: dict[str, tuple[float, float]] | None = None,
    penalty_scale: float = 1e6,
    meas_op: np.ndarray | None = None,
    fixed_alpha: tuple[float, float, float, float] | None = None,
) -> float:
    """Objective function for minimising Δω.

    Args:
        params: 11-element optimisation parameter vector, or 7-element
            state-only vector when fixed_alpha is set.
        omega_true: True phase rate parameter.
        ops: Two-qubit operators.
        fd_step: Finite-difference step size.
        bounds: Dict of parameter bounds (defaults to report values).
        penalty_scale: Scale for bound-violation penalty.
        meas_op: Measurement operator. Defaults to ops['Jz_S'].
        fixed_alpha: If set, params is a 7-element state vector;
            fixed_alpha is prepended to form the full 11-element vector.
            Alpha bound checks are skipped in this mode.

    Returns:
        Δω value (plus infinite penalty if bounds violated).

    """
    # Default bounds from the report
    if bounds is None:
        bounds = get_default_bounds()

    # If fixed_alpha is set, params is 7-element (state only);
    # prepend fixed_alpha to make 11 elements.
    if fixed_alpha is not None:
        params = np.concatenate([params, np.asarray(fixed_alpha, dtype=float)])

    theta_S, phi_S, theta_A, phi_A, T_BS1, T_BS2, t_hold, alpha = _params_to_components(
        params,
    )

    # --- Bound enforcement (penalty method) ---
    penalty = 0.0
    for val, key in [
        (theta_S, "bloch_theta"),
        (theta_A, "bloch_theta"),
        (phi_S, "phi"),
        (phi_A, "phi"),
        (T_BS1, "T_BS"),
        (T_BS2, "T_BS"),
        (t_hold, "t_hold"),
    ]:
        lo, hi = bounds[key]
        if val < lo:
            penalty += penalty_scale * (lo - val) ** 2
        if val > hi:
            penalty += penalty_scale * (val - hi) ** 2
    if fixed_alpha is None:
        for i in range(4):
            lo, hi = bounds["alpha"]
            if alpha[i] < lo:
                penalty += penalty_scale * (lo - alpha[i]) ** 2
            if alpha[i] > hi:
                penalty += penalty_scale * (alpha[i] - hi) ** 2

    if penalty > 0.0:
        return float(1e10 + penalty)

    # Build initial state
    psi0 = two_qubit_state(theta_S, phi_S, theta_A, phi_A)

    # Compute sensitivity
    return compute_sensitivity(
        psi0,
        T_BS1,
        T_BS2,
        t_hold,
        omega_true,
        alpha,
        ops,
        fd_step,
        meas_op=meas_op,
    )


# ============================================================================
# Nelder–Mead Optimisation
# ============================================================================


@dataclass
class OptimisationResult:
    """Result of a single Nelder–Mead run.

    Attributes:
        delta_omega_opt: Best sensitivity Δθ found (named in standard
            metrology notation; field kept for compatibility).
        meas_label: Measurement type — "S-only" or "Joint M".
        params_opt: Optimal 11-element parameter vector.
        omega_true: True ω used for this optimisation.
        success: Whether the optimiser reported success.
        nfev: Number of function evaluations.
        message: Optimiser message.
        expectation_Jz: ⟨J_z^S⟩ at the optimal operating point.
        variance_Jz: Var(J_z^S) at the optimal operating point.
        purity_S: Tr(ρ_S²) purity of the reduced system state (1 = pure,
            0.5 = maximally entangled with ancilla).
        expectation_M: ⟨J_z^S + J_z^A⟩ at the optimal operating point
            (for joint measurement).
        variance_M: Var(J_z^S + J_z^A) at the optimal operating point
            (for joint measurement).
        covariance_SA: Cov(J_z^S, J_z^A) at the optimal operating point
            (for joint measurement).
        history: Objective function values at each iteration (for
            convergence analysis). Empty list if callback not enabled.

    """

    delta_omega_opt: float
    params_opt: np.ndarray
    omega_true: float
    success: bool
    nfev: int
    message: str
    meas_label: str = "S-only"
    expectation_Jz: float = 0.0
    variance_Jz: float = 0.0
    purity_S: float = 0.0
    expectation_M: float = 0.0
    variance_M: float = 0.0
    covariance_SA: float = 0.0
    history: list[float] = field(default_factory=list)

    _PARQUET_COLUMNS: ClassVar[list[str]] = [
        "delta_omega_opt",
        "meas_label",
        "omega_true",
        "success",
        "nfev",
        "message",
        "expectation_Jz",
        "variance_Jz",
        "purity_S",
        "expectation_M",
        "variance_M",
        "covariance_SA",
        "theta_S",
        "phi_S",
        "theta_A",
        "phi_A",
        "T_BS1",
        "T_BS2",
        "t_hold",
        "alpha_xx",
        "alpha_xz",
        "alpha_zx",
        "alpha_zz",
    ]

    def to_dataframe(self) -> pd.DataFrame:
        """Single-row DataFrame with all metadata (history excluded, saved separately).

        Returns:
            DataFrame with one row containing all scalar fields and the 11
            optimisation parameters broken into named columns.

        """
        return pd.DataFrame(
            {
                "delta_omega_opt": [self.delta_omega_opt],
                "meas_label": [self.meas_label],
                "omega_true": [self.omega_true],
                "success": [int(self.success)],
                "nfev": [self.nfev],
                "message": [self.message],
                "expectation_Jz": [self.expectation_Jz],
                "variance_Jz": [self.variance_Jz],
                "purity_S": [self.purity_S],
                "expectation_M": [self.expectation_M],
                "variance_M": [self.variance_M],
                "covariance_SA": [self.covariance_SA],
                "theta_S": [float(self.params_opt[0])],
                "phi_S": [float(self.params_opt[1])],
                "theta_A": [float(self.params_opt[2])],
                "phi_A": [float(self.params_opt[3])],
                "T_BS1": [float(self.params_opt[4])],
                "T_BS2": [float(self.params_opt[5])],
                "t_hold": [float(self.params_opt[6])],
                "alpha_xx": [float(self.params_opt[7])],
                "alpha_xz": [float(self.params_opt[8])],
                "alpha_zx": [float(self.params_opt[9])],
                "alpha_zz": [float(self.params_opt[10])],
            },
        )

    def save_parquet(self, path: str | Path) -> Path:
        """Save to a Parquet file (scalars) with a sidecar history Parquet.

        Args:
            path: File path to write to.

        Returns:
            The path that was written to.

        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        self.to_dataframe().to_parquet(path, index=False)
        # Sidecar history file
        history_path = path.with_stem(path.stem + "-history")
        pd.DataFrame({"history": self.history}).to_parquet(history_path, index=False)
        return path

    @classmethod
    def from_parquet(cls, path: str | Path) -> OptimisationResult:
        """Reconstruct an OptimisationResult from a Parquet file.

        Args:
            path: Path to the Parquet file written by ``save_parquet``.

        Returns:
            Reconstructed OptimisationResult.

        Raises:
            ValueError: If the Parquet file is missing required columns.

        """
        path = Path(path)
        df = pd.read_parquet(path)
        missing = [c for c in cls._PARQUET_COLUMNS if c not in df.columns]
        if missing:
            raise ValueError(
                f"Parquet at {path} is missing required columns: "
                f"{sorted(missing)}. Regenerate the file with the current code."
            )
        params_opt = np.array(
            [
                float(df["theta_S"].iloc[0]),
                float(df["phi_S"].iloc[0]),
                float(df["theta_A"].iloc[0]),
                float(df["phi_A"].iloc[0]),
                float(df["T_BS1"].iloc[0]),
                float(df["T_BS2"].iloc[0]),
                float(df["t_hold"].iloc[0]),
                float(df["alpha_xx"].iloc[0]),
                float(df["alpha_xz"].iloc[0]),
                float(df["alpha_zx"].iloc[0]),
                float(df["alpha_zz"].iloc[0]),
            ],
        )
        history_path = path.with_stem(path.stem + "-history")
        history: list[float] = []
        if history_path.exists():
            history = pd.read_parquet(history_path)["history"].tolist()

        return cls(
            delta_omega_opt=float(df["delta_omega_opt"].iloc[0]),
            meas_label=str(df["meas_label"].iloc[0]),
            params_opt=params_opt,
            omega_true=float(df["omega_true"].iloc[0]),
            success=bool(int(df["success"].iloc[0])),
            nfev=int(df["nfev"].iloc[0]),
            message=str(df["message"].iloc[0]),
            expectation_Jz=float(df["expectation_Jz"].iloc[0]),
            variance_Jz=float(df["variance_Jz"].iloc[0]),
            purity_S=float(df["purity_S"].iloc[0]),
            expectation_M=float(df["expectation_M"].iloc[0]),
            variance_M=float(df["variance_M"].iloc[0]),
            covariance_SA=float(df["covariance_SA"].iloc[0]),
            history=history,
        )


@dataclass
class OmegaScanResult:
    """Results of an ω scan with multiple Nelder–Mead restarts per ω.

    Attributes:
        results: List of OptimisationResult per ω value.
        omega_values: Array of ω values scanned.
        best_per_omega: Best Δω for each ω value.
        all_results: All results (including non-best restarts) keyed by ω.

    """

    results: list[OptimisationResult] = field(default_factory=list)
    omega_values: np.ndarray = field(default_factory=lambda: np.array([]))
    best_per_omega: np.ndarray = field(default_factory=lambda: np.array([]))
    all_results: dict[float, list[OptimisationResult]] = field(default_factory=dict)

    def to_dataframe(self) -> pd.DataFrame:
        """Flatten the omega-scan results into a tabular DataFrame.

        One row per omega value with the best result and derived quantities.
        Works both from full results (with ``all_results`` populated) and
        from CSV-loaded summary (using ``omega_values`` / ``best_per_omega``).

        Returns:
            DataFrame with columns: omega, best_delta_omega, sql, vs_sql,
            spread, t_hold_star, covariance, expectation_M, flag.
        """
        rows: list[dict[str, float | str]] = []
        for i, omega_val in enumerate(self.omega_values):
            restarts = self.all_results.get(float(omega_val), [])
            if restarts:
                best = restarts[0]
                best_delta_omega = float(best.delta_omega_opt)
                spread = compute_convergence_metric(restarts)
                t_hold_star = float(best.params_opt[6])
                cov_val = float(best.covariance_SA)
                exp_m = float(best.expectation_M)
                vs_sql = (
                    float(best.delta_omega_opt / t_hold_star)
                    if t_hold_star > 0 and np.isfinite(1.0 / t_hold_star)
                    else float("inf")
                )
            else:
                # Summary-only mode (loaded from CSV)
                best_delta_omega = float(self.best_per_omega[i])
                spread = 0.0
                t_hold_star = 0.0
                cov_val = 0.0
                exp_m = 0.0
                vs_sql = float("inf")

            sql = 1.0 / t_hold_star if t_hold_star > 0 else float("inf")
            flag = "fringe" if abs(exp_m) < 1e-10 else "ok"

            rows.append(
                {
                    "omega": float(omega_val),
                    "best_delta_omega": best_delta_omega,
                    "sql": sql,
                    "vs_sql": vs_sql,
                    "spread": spread,
                    "t_hold_star": t_hold_star,
                    "covariance": cov_val,
                    "expectation_M": exp_m,
                    "flag": flag,
                },
            )
        return pd.DataFrame(rows)

    def save_parquet(self, path: str | Path) -> Path:
        """Save the omega-scan summary to a Parquet file.

        Args:
            path: File path to write to.

        Returns:
            The path that was written to.
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        self.to_dataframe().to_parquet(path, index=False)
        return path

    @classmethod
    def from_parquet(cls, path: str | Path) -> OmegaScanResult:
        """Reconstruct a OmegaScanResult from a Parquet file written by ``save_parquet``.

        Note: The reconstructed result contains only the summary per omega value
        (one row = one omega), not the full per-restart details.

        Args:
            path: Path to the Parquet file.

        Returns:
            A OmegaScanResult with the summary data.

        Raises:
            ValueError: If the Parquet file is missing required columns.
        """
        path = Path(path)
        df = pd.read_parquet(path)
        required = {"omega", "best_delta_omega", "sql"}
        missing = required - set(df.columns)
        if missing:
            raise ValueError(
                f"Parquet at {path} is missing required columns: "
                f"{sorted(missing)}. Regenerate the file with the current code."
            )
        omega_values = df["omega"].to_numpy(dtype=float)
        best_per_omega = df["best_delta_omega"].to_numpy(dtype=float)
        return cls(
            results=[],
            omega_values=omega_values,
            best_per_omega=best_per_omega,
            all_results={},
        )

    _RESTART_COLUMNS: ClassVar[list[str]] = [
        "omega",
        "restart_index",
        "delta_omega_opt",
        "meas_label",
        "omega_true",
        "success",
        "nfev",
        "message",
        "expectation_Jz",
        "variance_Jz",
        "purity_S",
        "expectation_M",
        "variance_M",
        "covariance_SA",
        "theta_S",
        "phi_S",
        "theta_A",
        "phi_A",
        "T_BS1",
        "T_BS2",
        "t_hold",
        "alpha_xx",
        "alpha_xz",
        "alpha_zx",
        "alpha_zz",
        "history_json",
    ]

    def to_restarts_dataframe(self) -> pd.DataFrame:
        """Flatten all per-restart results into a DataFrame.

        Returns:
            DataFrame with one row per restart, containing all optimisation
            parameters, diagnostics, and history as a JSON string.

        """
        rows: list[dict[str, object]] = []
        for omega_val in self.omega_values:
            restarts = self.all_results.get(float(omega_val), [])
            for idx, r in enumerate(restarts):
                params = r.params_opt
                rows.append(
                    {
                        "omega": float(omega_val),
                        "restart_index": idx,
                        "delta_omega_opt": r.delta_omega_opt,
                        "meas_label": r.meas_label,
                        "omega_true": r.omega_true,
                        "success": int(r.success),
                        "nfev": r.nfev,
                        "message": r.message,
                        "expectation_Jz": r.expectation_Jz,
                        "variance_Jz": r.variance_Jz,
                        "purity_S": r.purity_S,
                        "expectation_M": r.expectation_M,
                        "variance_M": r.variance_M,
                        "covariance_SA": r.covariance_SA,
                        "theta_S": float(params[0]),
                        "phi_S": float(params[1]),
                        "theta_A": float(params[2]),
                        "phi_A": float(params[3]),
                        "T_BS1": float(params[4]),
                        "T_BS2": float(params[5]),
                        "t_hold": float(params[6]),
                        "alpha_xx": float(params[7]),
                        "alpha_xz": float(params[8]),
                        "alpha_zx": float(params[9]),
                        "alpha_zz": float(params[10]),
                        "history_json": json.dumps(r.history),
                    },
                )
        return pd.DataFrame(rows)

    def save_restarts_parquet(self, path: str | Path) -> Path:
        """Save all per-restart data to a Parquet file.

        Args:
            path: File path to write to.

        Returns:
            The path that was written to.

        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        self.to_restarts_dataframe().to_parquet(path, index=False)
        return path

    @classmethod
    def from_restarts_parquet(cls, path: str | Path) -> OmegaScanResult:
        """Reconstruct a OmegaScanResult from a per-restart Parquet file.

        Args:
            path: Path to a Parquet file written by ``save_restarts_parquet``.

        Returns:
            A OmegaScanResult with ``all_results`` fully populated.

        Raises:
            ValueError: If the Parquet file is missing required columns.

        """
        path = Path(path)
        df = pd.read_parquet(path)
        missing = [c for c in cls._RESTART_COLUMNS if c not in df.columns]
        if missing:
            raise ValueError(
                f"Parquet at {path} is missing required columns: "
                f"{sorted(missing)}. Regenerate the file with the current code."
            )
        omega_values = sorted(df["omega"].unique())
        all_results: dict[float, list[OptimisationResult]] = {}
        for omega_val in omega_values:
            sub = df[df["omega"] == omega_val].sort_values("restart_index")
            restarts: list[OptimisationResult] = []
            for _, row in sub.iterrows():
                params_opt = np.array(
                    [
                        float(row["theta_S"]),
                        float(row["phi_S"]),
                        float(row["theta_A"]),
                        float(row["phi_A"]),
                        float(row["T_BS1"]),
                        float(row["T_BS2"]),
                        float(row["t_hold"]),
                        float(row["alpha_xx"]),
                        float(row["alpha_xz"]),
                        float(row["alpha_zx"]),
                        float(row["alpha_zz"]),
                    ],
                )
                history: list[float] = json.loads(str(row["history_json"]))
                restarts.append(
                    OptimisationResult(
                        delta_omega_opt=float(row["delta_omega_opt"]),
                        meas_label=str(row["meas_label"]),
                        params_opt=params_opt,
                        omega_true=float(row["omega_true"]),
                        success=bool(int(row["success"])),
                        nfev=int(row["nfev"]),
                        message=str(row["message"]),
                        expectation_Jz=float(row["expectation_Jz"]),
                        variance_Jz=float(row["variance_Jz"]),
                        purity_S=float(row["purity_S"]),
                        expectation_M=float(row["expectation_M"]),
                        variance_M=float(row["variance_M"]),
                        covariance_SA=float(row["covariance_SA"]),
                        history=history,
                    ),
                )
            restarts.sort(key=lambda r: r.delta_omega_opt)
            all_results[omega_val] = restarts
        omega_arr = np.array(omega_values, dtype=float)
        best_per_omega = np.array(
            [all_results[t][0].delta_omega_opt for t in omega_values],
            dtype=float,
        )
        results_flat = [r for rr in all_results.values() for r in rr]
        return cls(
            results=results_flat,
            omega_values=omega_arr,
            best_per_omega=best_per_omega,
            all_results=all_results,
        )


def get_default_bounds() -> dict[str, tuple[float, float]]:
    """Get the default parameter bounds.

    Returns:
        Dict with keys 'theta', 'phi', 'T_BS', 't_hold', 'alpha' mapping to
        (min, max) tuples.

    """
    return {
        "bloch_theta": (0.0, np.pi),
        "phi": (0.0, 2.0 * np.pi),
        "T_BS": (0.0, np.pi),
        "t_hold": (0.0, 5.0),
        "alpha": (-2.0, 2.0),
    }


def random_initial_params(
    rng: np.random.Generator,
    bounds: dict[str, tuple[float, float]] | None = None,
) -> np.ndarray:
    """Generate random initial parameters within the search bounds.

    All 11 parameters are drawn independently from their respective bounds.

    Args:
        rng: Random number generator.
        bounds: Optional custom bounds (uses defaults if None).

    Returns:
        11-element array of initial parameters.

    """
    if bounds is None:
        bounds = get_default_bounds()

    theta_lo, theta_hi = bounds["bloch_theta"]
    phi_lo, phi_hi = bounds["phi"]
    tbs_lo, tbs_hi = bounds["T_BS"]
    th_lo, th_hi = bounds["t_hold"]
    alpha_lo, alpha_hi = bounds["alpha"]

    theta_S, theta_A = rng.uniform(theta_lo, theta_hi, size=2)
    phi_S, phi_A = rng.uniform(phi_lo, phi_hi, size=2)
    T_BS1, T_BS2 = rng.uniform(tbs_lo, tbs_hi, size=2)
    t_hold = rng.uniform(th_lo, th_hi)
    alpha = rng.uniform(alpha_lo, alpha_hi, size=4)
    return np.array(
        [theta_S, phi_S, theta_A, phi_A, T_BS1, T_BS2, t_hold, *alpha],
        dtype=float,
    )


def run_optimisation(
    omega_true: float,
    ops: dict[str, np.ndarray],
    x0: np.ndarray | None = None,
    seed: int | None = None,
    maxiter: int = 5000,
    xatol: float = 1e-8,
    fatol: float = 1e-8,
    adaptive: bool = True,
    bounds: dict[str, tuple[float, float]] | None = None,
    track_history: bool = False,
    meas_op: np.ndarray | None = None,
    fixed_alpha: tuple[float, float, float, float] | None = None,
) -> OptimisationResult:
    """Run a single Nelder–Mead optimisation for ancilla-assisted metrology.

    Args:
        omega_true: True phase rate parameter.
        ops: Two-qubit operators.
        x0: Initial parameter vector (11 elements, or 7 when fixed_alpha is set).
            Random if None.
        seed: Random seed (used if x0 is None).
        maxiter: Maximum Nelder–Mead iterations.
        xatol: Absolute parameter tolerance.
        fatol: Absolute function tolerance.
        adaptive: Use adaptive Nelder–Mead parameters.
        bounds: Custom parameter bounds dictionary. Uses defaults if None.
        track_history: If True, record objective function values at each
            iteration in the result's `history` field.
        meas_op: Measurement operator for the objective.
            Defaults to ops['Jz_S'] (S-only).
        fixed_alpha: If set, optimisation is over state params only (7 elements)
            with the interaction coefficients held fixed.

    Returns:
        OptimisationResult with the best parameters found.

    """
    return _run_nelder_mead(
        omega_true=omega_true,
        ops=ops,
        x0=x0,
        seed=seed,
        maxiter=maxiter,
        xatol=xatol,
        fatol=fatol,
        adaptive=adaptive,
        bounds=bounds,
        track_history=track_history,
        meas_op=meas_op,
        fixed_alpha=fixed_alpha,
    )


def diagnostics_from_params(
    params: np.ndarray,
    omega_true: float,
    ops: dict[str, np.ndarray],
) -> tuple[float, float, float, float, float, float]:
    """Compute diagnostics (expectations, variances, covariance, purity) at a given parameter vector.

    Args:
        params: 11-element parameter vector (θ_S, φ_S, θ_A, φ_A, T_BS1, T_BS2, t_hold, α_xx, α_xz, α_zx, α_zz).
        omega_true: True phase rate parameter.
        ops: Two-qubit operators from build_two_qubit_operators().

    Returns:
        Tuple (exp_Jz, var_Jz, exp_M, var_M, cov_SA, purity).

    """
    (
        opt_theta_S,
        opt_phi_S,
        opt_theta_A,
        opt_phi_A,
        opt_T_BS1,
        opt_T_BS2,
        opt_t_hold,
        opt_alpha,
    ) = _params_to_components(params)
    opt_psi0 = two_qubit_state(opt_theta_S, opt_phi_S, opt_theta_A, opt_phi_A)
    opt_psi = evolve_full(
        opt_psi0,
        opt_T_BS1,
        opt_T_BS2,
        opt_t_hold,
        omega_true,
        opt_alpha,
        ops,
    )

    # Always compute both S-only and joint measurement diagnostics
    exp_val_s, var_val_s = compute_expectation_and_variance(opt_psi, ops["Jz_S"])
    M_op = build_joint_operator(ops)
    exp_val_m, var_val_m = compute_expectation_and_variance(opt_psi, M_op)
    cov_sa = compute_covariance(opt_psi, ops)
    purity = compute_reduced_purity(opt_psi)

    return exp_val_s, var_val_s, exp_val_m, var_val_m, cov_sa, purity


def _run_nelder_mead(
    omega_true: float,
    ops: dict[str, np.ndarray],
    x0: np.ndarray | None = None,
    seed: int | None = None,
    maxiter: int = 5000,
    xatol: float = 1e-8,
    fatol: float = 1e-8,
    adaptive: bool = True,
    bounds: dict[str, tuple[float, float]] | None = None,
    track_history: bool = False,
    meas_op: np.ndarray | None = None,
    fixed_alpha: tuple[float, float, float, float] | None = None,
) -> OptimisationResult:
    """Internal Nelder–Mead runner. Shared by run_optimisation and run_omega_scan.

    Args:
        omega_true: True phase rate parameter.
        ops: Two-qubit operators.
        x0: Initial parameter vector (11 elements, or 7 when fixed_alpha is set).
            Random if None.
        seed: Random seed (used if x0 is None).
        maxiter: Maximum Nelder–Mead iterations.
        xatol: Absolute parameter tolerance.
        fatol: Absolute function tolerance.
        adaptive: Use adaptive Nelder–Mead parameters.
        bounds: Custom parameter bounds dictionary. Uses defaults if None.
        track_history: If True, record objective function values per iteration.
        meas_op: Measurement operator for the objective.
            Defaults to ops['Jz_S'] (S-only).
        fixed_alpha: If set, optimisation is over state params only (7 elements)
            with the interaction coefficients held fixed.

    """
    if x0 is None:
        rng = np.random.default_rng(seed)
        x0 = random_initial_params(rng, bounds)
    else:
        x0 = np.asarray(x0, dtype=float)

    if fixed_alpha is not None:
        assert x0.shape in ((11,), (7,)), (
            f"x0 must have 7 or 11 elements when fixed_alpha is set, got {x0.shape}"
        )
        x0 = x0[:7]  # keep only state params
    else:
        assert x0.shape == (11,), "x0 must have 11 elements"

    # Objective function (closure over omega_true, ops, bounds, meas_op, fixed_alpha)
    def objective(p: np.ndarray) -> float:
        return sensitivity_objective(
            p, omega_true, ops, bounds=bounds, meas_op=meas_op, fixed_alpha=fixed_alpha
        )

    # History tracking via callback
    history: list[float] = []

    def callback(_x: np.ndarray) -> None:
        if track_history:
            val = objective(_x)
            history.append(val)

    result = minimize(
        objective,
        x0=x0,
        method="Nelder-Mead",
        callback=callback if track_history else None,  # type: ignore[arg-type]
        options={  # type: ignore[call-overload]
            "maxiter": maxiter,
            "xatol": xatol,
            "fatol": fatol,
            "adaptive": adaptive,
        },
    )

    # Compute expectation, variance, and purity at the optimal point
    # Use the full 11-element parameter vector for diagnostics
    opt_params = result.x.copy()
    if fixed_alpha is not None:
        opt_params = np.concatenate([opt_params, np.asarray(fixed_alpha, dtype=float)])
    (
        exp_val_s,
        var_val_s,
        exp_val_m,
        var_val_m,
        cov_sa,
        purity,
    ) = diagnostics_from_params(opt_params, omega_true, ops)

    # Determine measurement label by comparing meas_op to known operators
    if meas_op is None:
        meas_label = "S-only"
    else:
        # Compare against the canonical joint operator Jz_S + Jz_A
        joint_op = build_joint_operator(ops)
        if np.allclose(meas_op, joint_op, atol=1e-12):
            meas_label = "Joint M"
        else:
            meas_label = "Custom"

    return OptimisationResult(
        delta_omega_opt=float(result.fun),
        meas_label=meas_label,
        params_opt=opt_params,
        omega_true=omega_true,
        success=bool(result.success),
        nfev=int(result.nfev),
        message=str(result.message),
        expectation_Jz=exp_val_s,
        variance_Jz=var_val_s,
        purity_S=purity,
        expectation_M=exp_val_m,
        variance_M=var_val_m,
        covariance_SA=cov_sa,
        history=history.copy(),
    )


def run_omega_scan(
    omega_values: list[float] | np.ndarray,
    n_restarts: int = 10,
    seed: int | None = 42,
    maxiter: int = 5000,
    xatol: float = 1e-8,
    fatol: float = 1e-8,
    adaptive: bool = True,
    bounds: dict[str, tuple[float, float]] | None = None,
    track_history: bool = False,
    meas_op: np.ndarray | None = None,
) -> OmegaScanResult:
    """Scan over omega values with multiple Nelder–Mead restarts each.

    Args:
        omega_values: ω values to scan.
        n_restarts: Number of random-start Nelder–Mead runs per ω.
        seed: Base random seed (incremented per restart).
        maxiter: Maximum Nelder–Mead iterations per run.
        xatol: Absolute parameter tolerance.
        fatol: Absolute function tolerance.
        adaptive: Use adaptive Nelder–Mead parameters.
        bounds: Custom parameter bounds (e.g., to expand t_hold range).
            Default: t_hold ∈ [0, 5]. Use bounds={"t_hold": (0, 20), ...} for
            expanded-range experiments.
        track_history: If True, record convergence history per run.
        meas_op: Measurement operator for the objective.
            Defaults to ops['Jz_S'] (S-only).

    Returns:
        OmegaScanResult with all recorded information.

    """
    ops = build_two_qubit_operators()
    omega_arr = np.asarray(omega_values, dtype=float)
    base_seed = seed if seed is not None else 42

    all_results: dict[float, list[OptimisationResult]] = {}
    best_per_omega_list: list[float] = []
    all_results_flat: list[OptimisationResult] = []

    for omega_val in omega_arr:
        omega_results: list[OptimisationResult] = []
        for restart in range(n_restarts):
            rng = np.random.default_rng(base_seed + int(omega_val * 1000) + restart)
            x0 = random_initial_params(rng, bounds)
            opt_result = _run_nelder_mead(
                omega_true=omega_val,
                ops=ops,
                x0=x0,
                maxiter=maxiter,
                xatol=xatol,
                fatol=fatol,
                adaptive=adaptive,
                bounds=bounds,
                track_history=track_history,
                meas_op=meas_op,
            )
            omega_results.append(opt_result)
            all_results_flat.append(opt_result)

        # Sort by sensitivity (ascending)
        omega_results.sort(key=lambda r: r.delta_omega_opt)
        all_results[omega_val] = omega_results
        best_per_omega_list.append(omega_results[0].delta_omega_opt)

    return OmegaScanResult(
        results=all_results_flat,
        omega_values=omega_arr,
        best_per_omega=np.array(best_per_omega_list),
        all_results=all_results,
    )


# ============================================================================
# α-Scan with State Re-Optimisation
# ============================================================================


@dataclass
class AlphaReoptScanResult:
    """Result from scanning α with state re-optimisation at each point.

    Attributes:
        alpha_values: Array of α values scanned.
        delta_omega_joint: Best Δω for joint measurement at each α.
        delta_omega_sonly: Best Δω for S-only measurement at each α.
        best_params_joint: Full 11-element optimal params (joint) at each α.
        best_params_sonly: Full 11-element optimal params (S-only) at each α.

    """

    alpha_values: np.ndarray = field(default_factory=lambda: np.array([]))
    delta_omega_joint: np.ndarray = field(default_factory=lambda: np.array([]))
    delta_omega_sonly: np.ndarray = field(default_factory=lambda: np.array([]))
    best_params_joint: list[np.ndarray] = field(default_factory=list)
    best_params_sonly: list[np.ndarray] = field(default_factory=list)

    _PARAM_COLS: ClassVar[list[str]] = [
        "theta_S",
        "phi_S",
        "theta_A",
        "phi_A",
        "T_BS1",
        "T_BS2",
        "t_hold",
        "alpha_xx",
        "alpha_xz",
        "alpha_zx",
        "alpha_zz",
    ]

    def to_dataframe(self) -> pd.DataFrame:
        """Flatten the α re-optimisation scan into a DataFrame.

        Includes all metadata: optimal parameters for both joint and S-only
        measurements are stored in named columns alongside scalar results.

        Returns:
            DataFrame with columns: alpha, delta_omega_joint,
            delta_omega_sonly, and 22 optimal-parameter columns (11 per
            measurement type).

        """
        n = len(self.alpha_values)
        data: dict[str, object] = {
            "alpha": self.alpha_values,
            "delta_omega_joint": self.delta_omega_joint,
            "delta_omega_sonly": self.delta_omega_sonly,
        }

        # Pad or truncate params lists to match n
        def _pad(p: list[np.ndarray], n_target: int) -> list[np.ndarray]:
            if len(p) < n_target:
                return p + [np.full(11, float("nan"))] * (n_target - len(p))
            return p[:n_target]

        joint_params = _pad(self.best_params_joint, n)
        sonly_params = _pad(self.best_params_sonly, n)
        for i, col in enumerate(self._PARAM_COLS):
            data[f"joint_{col}"] = [float(p[i]) for p in joint_params]
            data[f"sonly_{col}"] = [float(p[i]) for p in sonly_params]
        return pd.DataFrame(data)

    def save_parquet(self, path: str | Path) -> Path:
        """Save to a Parquet file.

        Args:
            path: File path to write to.

        Returns:
            The path that was written to.
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        self.to_dataframe().to_parquet(path, index=False)
        return path

    @classmethod
    def from_parquet(cls, path: str | Path) -> AlphaReoptScanResult:
        """Reconstruct from a Parquet file.

        Args:
            path: Path to the Parquet file.

        Returns:
            Reconstructed AlphaReoptScanResult.

        Raises:
            ValueError: If the Parquet file is missing required columns.
        """
        df = pd.read_parquet(path)
        required = {
            "alpha",
            "delta_omega_joint",
            "delta_omega_sonly",
        }
        for side in ("joint", "sonly"):
            for col in cls._PARAM_COLS:
                required.add(f"{side}_{col}")
        missing = required - set(df.columns)
        if missing:
            raise ValueError(
                f"Parquet at {path} is missing required columns: "
                f"{sorted(missing)}. Regenerate the file with the current code."
            )
        n = len(df)
        best_params_joint: list[np.ndarray] = [
            np.array([float(df[f"joint_{col}"].iloc[i]) for col in cls._PARAM_COLS])
            for i in range(n)
        ]
        best_params_sonly: list[np.ndarray] = [
            np.array([float(df[f"sonly_{col}"].iloc[i]) for col in cls._PARAM_COLS])
            for i in range(n)
        ]
        return cls(
            alpha_values=df["alpha"].to_numpy(dtype=float),
            delta_omega_joint=df["delta_omega_joint"].to_numpy(dtype=float),
            delta_omega_sonly=df["delta_omega_sonly"].to_numpy(dtype=float),
            best_params_joint=best_params_joint,
            best_params_sonly=best_params_sonly,
        )


def scan_alpha_with_reoptimisation(
    alpha_name: str,
    alpha_values: np.ndarray | None = None,
    *,
    omega_true: float = 1.0,
    n_restarts: int = 5,
    maxiter: int = 500,
    seed: int = 42,
) -> AlphaReoptScanResult:
    """Scan a single α coefficient with state re-optimisation at each point.

    For each α value, the state parameters (θ_S, φ_S, θ_A, φ_A, T_BS1,
    T_BS2, t_hold) are re-optimised via Nelder–Mead while the interaction
    coefficients are held fixed.  Both joint and S-only measurement
    operators are evaluated independently.

    Args:
        alpha_name: Which coefficient to scan: 'xx', 'xz', 'zx', or 'zz'.
        alpha_values: Array of α values to scan.  Defaults to 21 points
            in [-2.0, 2.0].
        omega_true: True phase rate parameter (default 1.0).
        n_restarts: Number of random-start Nelder–Mead runs per α.
        maxiter: Maximum Nelder–Mead iterations per run.
        seed: Base random seed (incremented per restart).

    Returns:
        AlphaReoptScanResult with all recorded information.

    Raises:
        ValueError: If alpha_name is not one of 'xx', 'xz', 'zx', 'zz'.

    """
    alpha_idx_map = {"xx": 0, "xz": 1, "zx": 2, "zz": 3}
    if alpha_name not in alpha_idx_map:
        raise ValueError(
            f"alpha_name must be one of {list(alpha_idx_map.keys())}, got {alpha_name}",
        )
    scan_idx = alpha_idx_map[alpha_name]

    if alpha_values is None:
        alpha_values = np.linspace(-2.0, 2.0, 21)

    ops = build_two_qubit_operators()
    M_op = build_joint_operator(ops)

    alpha_arr = np.asarray(alpha_values, dtype=float)
    n_points = len(alpha_arr)

    delta_omega_joint = np.full(n_points, np.inf, dtype=float)
    delta_omega_sonly = np.full(n_points, np.inf, dtype=float)
    best_params_joint: list[np.ndarray] = []
    best_params_sonly: list[np.ndarray] = []

    for i, a_val in enumerate(alpha_arr):
        # Build the fixed α tuple: one coefficient varies, others zero
        alpha_list = [0.0, 0.0, 0.0, 0.0]
        alpha_list[scan_idx] = a_val
        fixed_alpha: tuple[float, float, float, float] = (
            alpha_list[0],
            alpha_list[1],
            alpha_list[2],
            alpha_list[3],
        )

        # --- Joint measurement ---
        joint_results: list[OptimisationResult] = []
        for restart in range(n_restarts):
            rng = np.random.default_rng(seed + i * 1000 + restart)
            x0 = random_initial_params(rng)[:7]  # 7 state params
            opt = _run_nelder_mead(
                omega_true=omega_true,
                ops=ops,
                x0=x0,
                maxiter=maxiter,
                meas_op=M_op,
                fixed_alpha=fixed_alpha,
            )
            joint_results.append(opt)
        joint_results.sort(key=lambda r: r.delta_omega_opt)
        delta_omega_joint[i] = joint_results[0].delta_omega_opt
        best_params_joint.append(joint_results[0].params_opt.copy())

        # --- S-only measurement ---
        sonly_results: list[OptimisationResult] = []
        for restart in range(n_restarts):
            rng = np.random.default_rng(seed + i * 1000 + restart + 10000)
            x0 = random_initial_params(rng)[:7]
            opt = _run_nelder_mead(
                omega_true=omega_true,
                ops=ops,
                x0=x0,
                maxiter=maxiter,
                meas_op=None,
                fixed_alpha=fixed_alpha,
            )
            sonly_results.append(opt)
        sonly_results.sort(key=lambda r: r.delta_omega_opt)
        delta_omega_sonly[i] = sonly_results[0].delta_omega_opt
        best_params_sonly.append(sonly_results[0].params_opt.copy())

    return AlphaReoptScanResult(
        alpha_values=alpha_arr,
        delta_omega_joint=delta_omega_joint,
        delta_omega_sonly=delta_omega_sonly,
        best_params_joint=best_params_joint,
        best_params_sonly=best_params_sonly,
    )


# ============================================================================
# Decoupled Baseline Result
# ============================================================================


@dataclass
class DecoupledBaselineResult:
    """Result from evaluating the decoupled baseline (α=0).

    Here α refers to the Ising coupling coefficient α_{zz} (not the scaling exponent).

    Attributes:
        t_hold_values: Array of holding-time values.
        delta_omega_values: Corresponding Δω (both joint and S-only give
            the same value in the decoupled case).
        sql_values: SQL = 1/t_hold values (time-based SQL; not particle-number SQL 1/√N).

    """

    t_hold_values: np.ndarray
    delta_omega_values: np.ndarray
    sql_values: np.ndarray

    def to_dataframe(self) -> pd.DataFrame:
        """Flatten into a DataFrame.

        Returns:
            DataFrame with columns: t_hold, delta_omega, sql, ratio.
        """
        return pd.DataFrame(
            {
                "t_hold": self.t_hold_values,
                "delta_omega": self.delta_omega_values,
                "sql": self.sql_values,
                "ratio": np.where(
                    self.sql_values > 0,
                    self.delta_omega_values / self.sql_values,
                    np.nan,
                ),
            },
        )

    def save_parquet(self, path: str | Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        self.to_dataframe().to_parquet(path, index=False)
        return path

    @classmethod
    def from_parquet(cls, path: str | Path) -> DecoupledBaselineResult:
        df = pd.read_parquet(path)
        required = {"t_hold", "delta_omega", "sql"}
        missing = required - set(df.columns)
        if missing:
            raise ValueError(
                f"Parquet at {path} is missing required columns: "
                f"{sorted(missing)}. Regenerate the file with the current code."
            )
        return cls(
            t_hold_values=df["t_hold"].to_numpy(dtype=float),
            delta_omega_values=df["delta_omega"].to_numpy(dtype=float),
            sql_values=df["sql"].to_numpy(dtype=float),
        )


def compute_decoupled_baseline(
    t_hold_values: np.ndarray,
    omega_true: float = 1.0,
) -> DecoupledBaselineResult:
    """Compute the decoupled baseline sensitivity Δω for a range of t_hold values.

    The optimal decoupled configuration is: system in |1,0⟩, ancilla in |1,0⟩,
    50/50 beam splitters, α=0.  At this configuration, Δω = 1/t_hold exactly.

    Args:
        t_hold_values: Array of holding-time strengths to evaluate.
        omega_true: True phase rate (default 1.0).

    Returns:
        DecoupledBaselineResult with computed sensitivities.
    """
    t_hold_arr = np.asarray(t_hold_values, dtype=float)
    delta_omega = np.array(
        [get_decoupled_sensitivity(t_hold, omega_true) for t_hold in t_hold_arr],
        dtype=float,
    )
    sql = 1.0 / t_hold_arr
    return DecoupledBaselineResult(
        t_hold_values=t_hold_arr,
        delta_omega_values=delta_omega,
        sql_values=sql,
    )


# ============================================================================
# Covariance Analysis Result
# ============================================================================


@dataclass
class CovarianceAnalysisResult:
    """Result from analysing Cov(J_z^S, J_z^A) across α coefficients.

    Attributes:
        coefficient_names: List of coefficient labels e.g. ['α_xx', ...].
        max_covariances: Max |Cov| for each coefficient over the scanned
            α range.
        covariance_signs: Sign of the max covariance (+1 or -1) for each
            coefficient.

    """

    coefficient_names: list[str]
    max_covariances: np.ndarray
    covariance_signs: np.ndarray

    def to_dataframe(self) -> pd.DataFrame:
        """Flatten into a DataFrame.

        Returns:
            DataFrame with columns: coefficient, max_covariance, sign.
        """
        return pd.DataFrame(
            {
                "coefficient": self.coefficient_names,
                "max_covariance": self.max_covariances,
                "sign": self.covariance_signs,
            },
        )

    def save_parquet(self, path: str | Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        self.to_dataframe().to_parquet(path, index=False)
        return path

    @classmethod
    def from_parquet(cls, path: str | Path) -> CovarianceAnalysisResult:
        df = pd.read_parquet(path)
        required = {"coefficient", "max_covariance", "sign"}
        missing = required - set(df.columns)
        if missing:
            raise ValueError(
                f"Parquet at {path} is missing required columns: "
                f"{sorted(missing)}. Regenerate the file with the current code."
            )
        return cls(
            coefficient_names=list(df["coefficient"]),
            max_covariances=df["max_covariance"].to_numpy(dtype=float),
            covariance_signs=df["sign"].to_numpy(dtype=float),
        )


def compute_covariance_analysis(
    alpha_range: tuple[float, float] = (-2.0, 2.0),
    n_points: int = 101,
    t_hold: float = 1.0,
    omega_true: float = 1.0,
) -> CovarianceAnalysisResult:
    """Compute max |Cov(J_z^S, J_z^A)| for each α coefficient type.

    Uses the analytically optimal decoupled state configuration
    (θ_S=0, θ_A=0, 50/50 BS).  Scans each α coefficient independently
    over ``alpha_range`` and records the maximum absolute covariance
    and its sign.

    Args:
        alpha_range: (min, max) for scanning each α coefficient.
        n_points: Number of points per scan.
        t_hold: Holding-time strength (default 1.0).
        omega_true: True phase rate (default 1.0).

    Returns:
        CovarianceAnalysisResult with max covariances and signs.
    """
    ops = build_two_qubit_operators()
    alpha_lo, alpha_hi = alpha_range
    alpha_scan = np.linspace(alpha_lo, alpha_hi, n_points)
    psi0 = two_qubit_state(0.0, 0.0, 0.0, 0.0)

    coeff_names = ["α_xx", "α_xz", "α_zx", "α_zz"]
    max_covs = np.zeros(4, dtype=float)
    cov_signs = np.zeros(4, dtype=float)

    for idx in range(4):
        covs = np.zeros(n_points, dtype=float)
        for j, a_val in enumerate(alpha_scan):
            alpha_list = [0.0, 0.0, 0.0, 0.0]
            alpha_list[idx] = a_val
            alpha: tuple[float, float, float, float] = (
                alpha_list[0],
                alpha_list[1],
                alpha_list[2],
                alpha_list[3],
            )
            psi = evolve_full(
                psi0, np.pi / 2, np.pi / 2, t_hold, omega_true, alpha, ops
            )
            covs[j] = compute_covariance(psi, ops)
        max_idx = int(np.argmax(np.abs(covs)))
        max_covs[idx] = abs(covs[max_idx])
        cov_signs[idx] = np.sign(covs[max_idx])

    return CovarianceAnalysisResult(
        coefficient_names=coeff_names,
        max_covariances=max_covs,
        covariance_signs=cov_signs,
    )


# ============================================================================
# Validation Helpers
# ============================================================================


def validate_operators(ops: dict[str, np.ndarray]) -> bool:
    """Validate all two-qubit operators.

    Checks: Hermiticity, commutation relations.

    Args:
        ops: Two-qubit operators.

    Returns:
        True if all checks pass.

    Raises:
        AssertionError: If any check fails.

    """
    for name, op in ops.items():
        assert op.shape == (4, 4), f"{name} must be 4×4, got {op.shape}"
        assert np.allclose(op, op.conj().T, atol=1e-12), f"{name} must be Hermitian"

    # Commutation: [J_z^S, J_x^S] = i J_y^S
    comm_zx_S = ops["Jz_S"] @ ops["Jx_S"] - ops["Jx_S"] @ ops["Jz_S"]
    assert np.allclose(comm_zx_S, 1j * ops["Jy_S"], atol=1e-12), (
        "[Jz_S, Jx_S] = i Jy_S failed"
    )

    # Commutation: [J_z^A, J_x^A] = i J_y^A
    comm_zx_A = ops["Jz_A"] @ ops["Jx_A"] - ops["Jx_A"] @ ops["Jz_A"]
    assert np.allclose(comm_zx_A, 1j * ops["Jy_A"], atol=1e-12), (
        "[Jz_A, Jx_A] = i Jy_A failed"
    )

    return True


def validate_bs_unitarity(T_BS: float = np.pi / 4) -> bool:
    """Validate the beam-splitter unitary.

    Args:
        T_BS: Beam-splitter duration.

    Returns:
        True if unitary.

    """
    U = bs_unitary(T_BS)
    assert np.allclose(U @ U.conj().T, I_2, atol=1e-12), "BS must be unitary"
    assert np.allclose(U.conj().T @ U, I_2, atol=1e-12), "BS† must be unitary"
    return True


def validate_two_qubit_bs_unitarity(T_BS: float = np.pi / 4) -> bool:
    """Validate the two-qubit beam-splitter unitary.

    Args:
        T_BS: Beam-splitter duration.

    Returns:
        True if unitary.

    """
    U = two_qubit_bs_unitary(T_BS)
    assert np.allclose(U @ U.conj().T, I_4, atol=1e-12), "2-qubit BS must be unitary"
    return True


def validate_hold_unitarity(
    t_hold: float = 1.0,
    omega: float = 1.0,
    alpha: tuple[float, float, float, float] = (0.1, 0.0, 0.0, 0.0),
) -> bool:
    """Validate the hold unitary.

    Args:
        t_hold: Holding time.
        omega: Phase rate.
        alpha: Interaction coefficients.

    Returns:
        True if unitary.

    """
    ops = build_two_qubit_operators()
    U = hold_unitary_two_qubit(t_hold, omega, alpha, ops)
    assert np.allclose(U @ U.conj().T, I_4, atol=1e-12), "Hold must be unitary"
    return True


def validate_sensitivity_reasonable(
    t_hold_vals: list[float] | None = None,
) -> bool:
    """Verify that sensitivity Δω ≈ 1/t_hold in the decoupled (α=0) case.

    Checks that the analytically optimal configuration achieves Δω ≈ 1/t_hold
    when the interaction is off.

    Args:
        t_hold_vals: Holding-time values to check.

    Returns:
        True if all checks pass.

    """
    if t_hold_vals is None:
        t_hold_vals = [0.5, 1.0, 2.0]

    ops = build_two_qubit_operators()

    # Analytic optimum for decoupled case:
    # |ψ_S⟩ = |1,0⟩, 50/50 beam splitters (T = π/2)
    theta_S, phi_S = 0.0, 0.0  # |1,0⟩
    theta_A, phi_A = 0.0, 0.0  # |1,0⟩ (ancilla doesn't matter)
    alpha = (0.0, 0.0, 0.0, 0.0)
    T_BS = np.pi / 2.0

    psi0 = two_qubit_state(theta_S, phi_S, theta_A, phi_A)

    for t_hold in t_hold_vals:
        # Use θ_true = 1.0 (away from fringe extremum)
        domega = compute_sensitivity(psi0, T_BS, T_BS, t_hold, 1.0, alpha, ops)
        expected = 1.0 / t_hold
        # Relative tolerance 5% to account for finite-difference and
        # residual fringe effects
        assert np.isclose(domega, expected, rtol=0.05), (
            f"Δω = {domega:.6f} for t_hold={t_hold}, expected ≈ {expected:.6f}"
        )

    return True


def validate_variance_positive(
    psi: np.ndarray,
    operator: np.ndarray,
    atol: float = 1e-12,
) -> bool:
    """Validate that Var(O) ≥ -atol for a given state and operator.

    A slightly negative variance (order 1e-16) can arise from numerical
    rounding; this function asserts it is not significantly negative.

    Args:
        psi: Normalised state vector.
        operator: Hermitian operator matrix.
        atol: Absolute tolerance for negative variance (default 1e-12).

    Returns:
        True if check passes.

    Raises:
        AssertionError: If variance < -atol (unphysical).

    """
    _, var = compute_expectation_and_variance(psi, operator)
    assert var >= -atol, f"Unphysical negative variance: Var = {var:.2e}"
    return True


def validate_derivative_stability(
    psi0: np.ndarray,
    T_BS1: float,
    T_BS2: float,
    t_hold: float,
    omega_true: float,
    alpha: tuple[float, float, float, float],
    ops: dict[str, np.ndarray],
    fd_steps: tuple[float, float, float] = (1e-5, 1e-6, 1e-7),
    rtol: float = 0.02,
) -> bool:
    """Check that the finite-difference derivative is stable w.r.t. step size.

    Computes Δω at multiple fd_step values and asserts the relative spread
    is below `rtol`.  This validates that the default fd_step = 1e-6 is not
    in a noisy regime.

    Args:
        psi0: Initial 4-vector (product state).
        T_BS1: First beam-splitter duration.
        T_BS2: Second beam-splitter duration.
        t_hold: Holding-time strength.
        omega_true: True phase rate parameter.
        alpha: (α_xx, α_xz, α_zx, α_zz) coupling coefficients.
        ops: Two-qubit operators (must contain 'Jz_S').
        fd_steps: Three fd_step values to compare (default 1e-5, 1e-6, 1e-7).
        rtol: Maximum allowed relative spread (default 0.02 = 2%).

    Returns:
        True if all checks pass.

    Raises:
        AssertionError: If derivative is unstable across step sizes.

    """
    sensitivities: list[float] = []
    for step in fd_steps:
        domega = compute_sensitivity(
            psi0,
            T_BS1,
            T_BS2,
            t_hold,
            omega_true,
            alpha,
            ops,
            fd_step=step,
        )
        if not np.isfinite(domega):
            # Skip fringe-extremum configurations
            continue
        sensitivities.append(domega)

    if len(sensitivities) < 2:
        # Not enough finite values to compare — skip (likely at fringe extremum)
        return True

    arr = np.array(sensitivities)
    mean_val = float(np.mean(arr))
    if mean_val == 0.0:
        return True

    # Max relative deviation from the mean
    max_dev = float(np.max(np.abs(arr - mean_val) / mean_val))
    assert max_dev < rtol, (
        f"Derivative unstable across fd_steps {fd_steps}: "
        f"sensitivities = {sensitivities}, max relative deviation = {max_dev:.4f}"
    )
    return True


# ============================================================================
# Convenience Runner
# ============================================================================


def compute_convergence_metric(
    results: list[OptimisationResult],
) -> float:
    """Compute the convergence spread metric for a set of restarts.

    Returns std(Δω) / mean(Δω) for the given results. A value < 0.10
    indicates consistent convergence across restarts (Success Criterion #1).

    Args:
        results: List of OptimisationResult for a given θ (all restarts).

    Returns:
        Relative standard deviation (spread / mean). Returns 0.0 if
        fewer than 2 results are provided or mean is zero.

    """
    if len(results) < 2:
        return 0.0
    deltas = np.array([r.delta_omega_opt for r in results])
    # Filter out infinite values (fringe-extremum results)
    finite = deltas[np.isfinite(deltas)]
    if len(finite) < 2:
        return 0.0
    mean_val = float(np.mean(finite))
    if mean_val == 0.0:
        return 0.0
    return float(np.std(finite, ddof=1) / mean_val)


def get_decoupled_sensitivity(t_hold: float, omega_true: float = 1.0) -> float:
    """Compute the SQL sensitivity for the decoupled (α=0) case.

    Optimal configuration: system in |1,0⟩, 50/50 beam splitters, no interaction.

    Args:
        t_hold: Holding-time strength.
        omega_true: True phase rate.

    Returns:
        Δω (ideally = 1/t_hold).

    """
    ops = build_two_qubit_operators()
    psi0 = two_qubit_state(0.0, 0.0, 0.0, 0.0)  # both in |1,0⟩
    T_BS = np.pi / 2.0
    alpha = (0.0, 0.0, 0.0, 0.0)
    return compute_sensitivity(psi0, T_BS, T_BS, t_hold, omega_true, alpha, ops)


# ============================================================================
# α-Coefficient Scans (Grid and Random Search)
# ============================================================================


@dataclass
class AlphaSingleScanResult:
    """Result from scanning a single α coefficient while holding others fixed.

    Attributes:
        alpha_name: Which coefficient was scanned ('xx', 'xz', 'zx', 'zz').
        alpha_values: Array of α values scanned.
        delta_omega_values: Corresponding Δω sensitivity values.
        fixed_params: Dict of the other fixed parameters used.

    """

    alpha_name: str
    alpha_values: np.ndarray
    delta_omega_values: np.ndarray
    fixed_params: dict[str, float] = field(default_factory=dict)

    def to_dataframe(self) -> pd.DataFrame:
        """Flatten the single-α scan into a DataFrame.

        Returns:
            DataFrame with columns: alpha_name, alpha, delta_omega,
            and fixed_params serialised as JSON.

        """
        return pd.DataFrame(
            {
                "alpha_name": [self.alpha_name] * len(self.alpha_values),
                "alpha": self.alpha_values,
                "delta_omega": self.delta_omega_values,
                "fixed_params_json": [json.dumps(self.fixed_params)]
                * len(self.alpha_values),
            },
        )

    def save_parquet(self, path: str | Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        self.to_dataframe().to_parquet(path, index=False)
        return path

    @classmethod
    def from_parquet(cls, path: str | Path) -> AlphaSingleScanResult:
        df = pd.read_parquet(path)
        required = {"alpha_name", "alpha", "delta_omega", "fixed_params_json"}
        missing = required - set(df.columns)
        if missing:
            raise ValueError(
                f"Parquet at {path} is missing required columns: "
                f"{sorted(missing)}. Regenerate the file with the current code."
            )
        return cls(
            alpha_name=str(df["alpha_name"].iloc[0]),
            alpha_values=df["alpha"].to_numpy(dtype=float),
            delta_omega_values=df["delta_omega"].to_numpy(dtype=float),
            fixed_params=json.loads(str(df["fixed_params_json"].iloc[0])),
        )


@dataclass
class AlphaRandomSearchResult:
    """Result from random search over the 4D α coefficient space.

    Attributes:
        alpha_samples: Array of shape (N, 4) with sampled α values.
        delta_omega_values: Array of shape (N,) with Δω for each sample.
        best_alpha: The α = (α_xx, α_xz, α_zx, α_zz) that gave minimal Δω.
        best_delta_omega: The minimal Δω found.
        fixed_params: Dict of the other fixed parameters used.

    """

    alpha_samples: np.ndarray
    delta_omega_values: np.ndarray
    best_alpha: tuple[float, float, float, float]
    best_delta_omega: float
    fixed_params: dict[str, float] = field(default_factory=dict)

    def to_dataframe(self) -> pd.DataFrame:
        """Flatten the random search into a DataFrame.

        Returns:
            DataFrame with columns: alpha_xx, alpha_xz, alpha_zx,
            alpha_zz, delta_omega, fixed_params_json.

        """
        return pd.DataFrame(
            {
                "alpha_xx": self.alpha_samples[:, 0],
                "alpha_xz": self.alpha_samples[:, 1],
                "alpha_zx": self.alpha_samples[:, 2],
                "alpha_zz": self.alpha_samples[:, 3],
                "delta_omega": self.delta_omega_values,
                "fixed_params_json": [json.dumps(self.fixed_params)]
                * len(self.delta_omega_values),
            },
        )

    def save_parquet(self, path: str | Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        self.to_dataframe().to_parquet(path, index=False)
        return path

    @classmethod
    def from_parquet(cls, path: str | Path) -> AlphaRandomSearchResult:
        df = pd.read_parquet(path)
        required = {
            "alpha_xx",
            "alpha_xz",
            "alpha_zx",
            "alpha_zz",
            "delta_omega",
            "fixed_params_json",
        }
        missing = required - set(df.columns)
        if missing:
            raise ValueError(
                f"Parquet at {path} is missing required columns: "
                f"{sorted(missing)}. Regenerate the file with the current code."
            )
        alphas = df[["alpha_xx", "alpha_xz", "alpha_zx", "alpha_zz"]].to_numpy(
            dtype=float
        )
        deltas = df["delta_omega"].to_numpy(dtype=float)
        best_idx = int(np.argmin(deltas))
        return cls(
            alpha_samples=alphas,
            delta_omega_values=deltas,
            best_alpha=(
                float(alphas[best_idx, 0]),
                float(alphas[best_idx, 1]),
                float(alphas[best_idx, 2]),
                float(alphas[best_idx, 3]),
            ),
            best_delta_omega=float(deltas[best_idx]),
            fixed_params=json.loads(str(df["fixed_params_json"].iloc[0])),
        )


def scan_alpha_single_parameter(
    alpha_name: str,
    alpha_min: float = -2.0,
    alpha_max: float = 2.0,
    n_points: int = 21,
    *,
    theta_S: float = np.pi / 2,
    phi_S: float = 0.0,
    theta_A: float = 0.0,
    phi_A: float = 0.0,
    T_BS1: float = np.pi / 2,
    T_BS2: float = np.pi / 2,
    t_hold: float = 1.0,
    omega_true: float = 1.0,
    meas_op: np.ndarray | None = None,
) -> AlphaSingleScanResult:
    """Scan a single α coefficient while holding others fixed.

    This replicates the grid scan described in the report: "each α_ij is
    scanned independently in [-2, 2] with 21 points, while the other three
    are held at zero."

    Physical configuration defaults (SQL-optimal for α=0):
        - System: |ψ_S⟩ = (|0⟩ + |1⟩)/√2 (θ_S = π/2)
        - Ancilla: |ψ_A⟩ = |0⟩ (θ_A = 0)
        - Beam splitters: 50/50 (T_BS1 = T_BS2 = π/2)
        - t_hold = 1.0, ω_true = 1.0

    Args:
        alpha_name: Which coefficient to scan: 'xx', 'xz', 'zx', or 'zz'.
        alpha_min: Minimum value for the scan (default -2.0).
        alpha_max: Maximum value for the scan (default 2.0).
        n_points: Number of points in the scan (default 21).
        theta_S: System polar angle (default π/2).
        phi_S: System azimuthal angle (default 0.0).
        theta_A: Ancilla polar angle (default 0.0).
        phi_A: Ancilla azimuthal angle (default 0.0).
        T_BS1: First beam-splitter duration (default π/2).
        T_BS2: Second beam-splitter duration (default π/2).
        t_hold: Holding time (default 1.0).
        omega_true: True phase rate (default 1.0).
        meas_op: Measurement operator. Defaults to ops['Jz_S'] (S-only).

    Returns:
        AlphaSingleScanResult with scanned values and sensitivities.

    Raises:
        ValueError: If alpha_name is not one of 'xx', 'xz', 'zx', 'zz'.

    """
    alpha_idx_map = {"xx": 0, "xz": 1, "zx": 2, "zz": 3}
    if alpha_name not in alpha_idx_map:
        raise ValueError(
            f"alpha_name must be one of {list(alpha_idx_map.keys())}, got {alpha_name}",
        )
    scan_idx = alpha_idx_map[alpha_name]

    ops = build_two_qubit_operators()
    if meas_op is None:
        meas_op = ops["Jz_S"]
    psi0 = two_qubit_state(theta_S, phi_S, theta_A, phi_A)

    alpha_values = np.linspace(alpha_min, alpha_max, n_points)
    delta_omega_values = np.zeros(n_points, dtype=float)

    for i, a_val in enumerate(alpha_values):
        alpha_list = [0.0, 0.0, 0.0, 0.0]
        alpha_list[scan_idx] = a_val
        alpha: tuple[float, float, float, float] = (
            alpha_list[0],
            alpha_list[1],
            alpha_list[2],
            alpha_list[3],
        )
        domega = compute_sensitivity(
            psi0,
            T_BS1,
            T_BS2,
            t_hold,
            omega_true,
            alpha,
            ops,
            meas_op=meas_op,
        )
        delta_omega_values[i] = domega

    fixed_params = {
        "theta_S": theta_S,
        "phi_S": phi_S,
        "theta_A": theta_A,
        "phi_A": phi_A,
        "T_BS1": T_BS1,
        "T_BS2": T_BS2,
        "t_hold": t_hold,
        "omega_true": omega_true,
    }

    return AlphaSingleScanResult(
        alpha_name=alpha_name,
        alpha_values=alpha_values,
        delta_omega_values=delta_omega_values,
        fixed_params=fixed_params,
    )


def random_search_alpha(
    n_samples: int = 200,
    alpha_min: float = -2.0,
    alpha_max: float = 2.0,
    *,
    theta_S: float = np.pi / 2,
    phi_S: float = 0.0,
    theta_A: float = 0.0,
    phi_A: float = 0.0,
    T_BS1: float = np.pi / 2,
    T_BS2: float = np.pi / 2,
    t_hold: float = 1.0,
    omega_true: float = 1.0,
    seed: int | None = 42,
    meas_op: np.ndarray | None = None,
) -> AlphaRandomSearchResult:
    """Random search over the 4D α = (α_xx, α_xz, α_zx, α_zz) space.

    This replicates the random search described in the report: "200 samples
    over the full 4D α space" to verify that no combination achieves
    Δω < 1/t_hold (SQL).

    Args:
        n_samples: Number of random α samples to evaluate (default 200).
        alpha_min: Lower bound for all α coefficients (default -2.0).
        alpha_max: Upper bound for all α coefficients (default 2.0).
        theta_S: System polar angle (default π/2).
        phi_S: System azimuthal angle (default 0.0).
        theta_A: Ancilla polar angle (default 0.0).
        phi_A: Ancilla azimuthal angle (default 0.0).
        T_BS1: First beam-splitter duration (default π/2).
        T_BS2: Second beam-splitter duration (default π/2).
        t_hold: Holding time (default 1.0).
        omega_true: True phase rate (default 1.0).
        seed: Random seed for reproducibility (default 42).
        meas_op: Measurement operator. Defaults to ops['Jz_S'] (S-only).

    Returns:
        AlphaRandomSearchResult with all samples and the best found.

    """
    rng = np.random.default_rng(seed)
    ops = build_two_qubit_operators()
    if meas_op is None:
        meas_op = ops["Jz_S"]
    psi0 = two_qubit_state(theta_S, phi_S, theta_A, phi_A)

    # Sample uniformly in [alpha_min, alpha_max]^4
    alpha_samples = rng.uniform(alpha_min, alpha_max, size=(n_samples, 4))
    delta_omega_values = np.zeros(n_samples, dtype=float)

    for i in range(n_samples):
        alpha: tuple[float, float, float, float] = (
            float(alpha_samples[i, 0]),
            float(alpha_samples[i, 1]),
            float(alpha_samples[i, 2]),
            float(alpha_samples[i, 3]),
        )
        domega = compute_sensitivity(
            psi0,
            T_BS1,
            T_BS2,
            t_hold,
            omega_true,
            alpha,
            ops,
            meas_op=meas_op,
        )
        delta_omega_values[i] = domega

    # Find best (minimal Δω)
    best_idx = int(np.argmin(delta_omega_values))
    best_alpha: tuple[float, float, float, float] = (
        float(alpha_samples[best_idx, 0]),
        float(alpha_samples[best_idx, 1]),
        float(alpha_samples[best_idx, 2]),
        float(alpha_samples[best_idx, 3]),
    )
    best_delta_omega = float(delta_omega_values[best_idx])

    fixed_params = {
        "theta_S": theta_S,
        "phi_S": phi_S,
        "theta_A": theta_A,
        "phi_A": phi_A,
        "T_BS1": T_BS1,
        "T_BS2": T_BS2,
        "t_hold": t_hold,
        "omega_true": omega_true,
    }

    return AlphaRandomSearchResult(
        alpha_samples=alpha_samples,
        delta_omega_values=delta_omega_values,
        best_alpha=best_alpha,
        best_delta_omega=best_delta_omega,
        fixed_params=fixed_params,
    )


# ============================================================================
# Interaction Robustness Scan (t_hold × α)
# ============================================================================


@dataclass
class InteractionRobustnessResult:
    """Result from a 2D scan over t_hold and α values.

    Attributes:
        t_hold_values: Array of t_hold holding-time values scanned.
        alpha_values: Array of α coefficient values scanned.
        delta_omega_joint: 2D array of Δω (joint measurement) for each
            (t_hold, α) pair, shape (len(t_hold_values), len(alpha_values)).
        delta_omega_sonly: 2D array of Δω (S-only measurement) for each
            (t_hold, α) pair, shape (len(t_hold_values), len(alpha_values)).

    """

    t_hold_values: np.ndarray = field(default_factory=lambda: np.array([]))
    alpha_values: np.ndarray = field(default_factory=lambda: np.array([]))
    delta_omega_joint: np.ndarray = field(default_factory=lambda: np.array([]))
    delta_omega_sonly: np.ndarray = field(default_factory=lambda: np.array([]))

    def to_dataframe(self) -> pd.DataFrame:
        """Melt the 2D arrays into a long-format DataFrame.

        Returns:
            DataFrame with columns: t_hold, alpha, measurement, delta_omega.
        """
        n_T = len(self.t_hold_values)
        n_a = len(self.alpha_values)
        rows: list[dict[str, float | str]] = []
        for i in range(n_T):
            for j in range(n_a):
                rows.append(
                    {
                        "t_hold": float(self.t_hold_values[i]),
                        "alpha": float(self.alpha_values[j]),
                        "measurement": "joint",
                        "delta_omega": float(self.delta_omega_joint[i, j]),
                    },
                )
                rows.append(
                    {
                        "t_hold": float(self.t_hold_values[i]),
                        "alpha": float(self.alpha_values[j]),
                        "measurement": "sonly",
                        "delta_omega": float(self.delta_omega_sonly[i, j]),
                    },
                )
        return pd.DataFrame(rows)

    def save_parquet(self, path: str | Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        self.to_dataframe().to_parquet(path, index=False)
        return path

    @classmethod
    def from_parquet(cls, path: str | Path) -> InteractionRobustnessResult:
        df = pd.read_parquet(path)
        required = {"t_hold", "alpha", "measurement", "delta_omega"}
        missing = required - set(df.columns)
        if missing:
            raise ValueError(
                f"Parquet at {path} is missing required columns: "
                f"{sorted(missing)}. Regenerate the file with the current code."
            )
        t_hold_unique = sorted(df["t_hold"].unique())
        alpha_unique = sorted(df["alpha"].unique())
        n_T = len(t_hold_unique)
        n_a = len(alpha_unique)
        dtheta_j = np.full((n_T, n_a), np.nan)
        dtheta_s = np.full((n_T, n_a), np.nan)
        for _, row in df.iterrows():
            i = t_hold_unique.index(row["t_hold"])
            j = alpha_unique.index(row["alpha"])
            if row["measurement"] == "joint":
                dtheta_j[i, j] = row["delta_omega"]
            else:
                dtheta_s[i, j] = row["delta_omega"]
        return cls(
            t_hold_values=np.array(t_hold_unique, dtype=float),
            alpha_values=np.array(alpha_unique, dtype=float),
            delta_omega_joint=dtheta_j,
            delta_omega_sonly=dtheta_s,
        )


def compute_interaction_robustness(
    t_hold_values: np.ndarray,
    alpha_values: np.ndarray,
    *,
    omega_true: float = 1.0,
    alpha_name: str = "xx",
    theta_S: float = 0.0,
    phi_S: float = 0.0,
    theta_A: float = 0.0,
    phi_A: float = 0.0,
    T_BS: float = np.pi / 2,
) -> InteractionRobustnessResult:
    """Scan over t_hold and a single α coefficient, recording sensitivity for
    both S-only and joint measurements.

    For each (t_hold, α) pair, the state and beam-splitter parameters are
    held fixed while the holding-time strength and interaction coefficient
    are varied.  The sensitivity Δω is computed via `compute_sensitivity`
    for both measurement operators (S-only and joint).

    Args:
        t_hold_values: Array of t_hold holding-time strengths to scan.
        alpha_values: Array of α coefficient values to scan (single
            coefficient determined by `alpha_name`).
        omega_true: True phase rate parameter (default 1.0).
        alpha_name: Which coefficient to scan: 'xx', 'xz', 'zx', or 'zz'
            (default 'xx').
        theta_S: System polar angle (default 0.0).
        phi_S: System azimuthal angle (default 0.0).
        theta_A: Ancilla polar angle (default 0.0).
        phi_A: Ancilla azimuthal angle (default 0.0).
        T_BS: Beam-splitter duration for both first and second beam
            splitters (default π/2).

    Returns:
        InteractionRobustnessResult containing the 2D sensitivity arrays.

    Raises:
        ValueError: If alpha_name is not one of 'xx', 'xz', 'zx', 'zz'.

    """
    alpha_idx_map = {"xx": 0, "xz": 1, "zx": 2, "zz": 3}
    if alpha_name not in alpha_idx_map:
        raise ValueError(
            f"alpha_name must be one of {list(alpha_idx_map.keys())}, got {alpha_name}",
        )
    scan_idx = alpha_idx_map[alpha_name]

    ops = build_two_qubit_operators()
    M_op = build_joint_operator(ops)
    psi0 = two_qubit_state(theta_S, phi_S, theta_A, phi_A)

    t_hold_arr = np.asarray(t_hold_values, dtype=float)
    alpha_arr = np.asarray(alpha_values, dtype=float)
    n_t_hold = len(t_hold_arr)
    n_alpha = len(alpha_arr)

    delta_omega_joint = np.full((n_t_hold, n_alpha), np.inf, dtype=float)
    delta_omega_sonly = np.full((n_t_hold, n_alpha), np.inf, dtype=float)

    for i, t_hold in enumerate(t_hold_arr):
        for j, a_val in enumerate(alpha_arr):
            alpha_list = [0.0, 0.0, 0.0, 0.0]
            alpha_list[scan_idx] = a_val
            alpha: tuple[float, float, float, float] = (
                alpha_list[0],
                alpha_list[1],
                alpha_list[2],
                alpha_list[3],
            )

            # S-only measurement (meas_op=None defaults to Jz_S)
            dtheta_s = compute_sensitivity(
                psi0,
                T_BS,
                T_BS,
                t_hold,
                omega_true,
                alpha,
                ops,
                meas_op=None,
            )
            delta_omega_sonly[i, j] = dtheta_s

            # Joint measurement (Jz_S + Jz_A)
            dtheta_j = compute_sensitivity(
                psi0,
                T_BS,
                T_BS,
                t_hold,
                omega_true,
                alpha,
                ops,
                meas_op=M_op,
            )
            delta_omega_joint[i, j] = dtheta_j

    return InteractionRobustnessResult(
        t_hold_values=t_hold_arr,
        alpha_values=alpha_arr,
        delta_omega_joint=delta_omega_joint,
        delta_omega_sonly=delta_omega_sonly,
    )
